/* GENERATED by DesignLang.scala - DO NOT EDIT. Theme toggle for the genscalator design
   language: flips body.dark, persists in localStorage, first load follows the OS scheme.
   Requires a <button id="theme-toggle"> on the page (styled by design.css). */
(function () {
  var btn = document.getElementById('theme-toggle');
  if (!btn) return;
  function label() { btn.textContent = document.body.classList.contains('dark') ? 'Smither light' : 'Forgy dark'; }
  var saved = localStorage.getItem('gs-design-theme');
  if (saved === 'dark' || (saved === null && window.matchMedia('(prefers-color-scheme: dark)').matches))
    document.body.classList.add('dark');
  label();
  btn.addEventListener('click', function () {
    document.body.classList.toggle('dark');
    localStorage.setItem('gs-design-theme', document.body.classList.contains('dark') ? 'dark' : 'light');
    label();
  });
})();
