//> using scala 3.8.4
//> using file ../../tools/lib.scala
//> using file ../../tools/mdparse.scala
//> using file ../../tools/ssg.scala
// NB all three declared here: `using file` does NOT chain, so ssg's own file-directives are
// inert when ssg.scala is included this way. Two @mains in the unit (ssg's + ours) ⇒ run with:
//   scala-cli run . --main-class generateDesignLanguage
// DesignLang — THE single point of truth for the genscalator design language (SM155/T8).
// Effectful driver by design (visible effects only at the end): generates README.md,
// index.html (the README rendered through the house Ssg.renderPage — one parser, one more
// consumer), preview-GENERATED.html and logo-lab-GENERATED.html next to this file (or into
// the dir given as the single optional arg). Everything else in this folder is OUTPUT — edit HERE, re-run:
//   scala-cli run media/design-language/DesignLang.scala
// Grew from contrast.scala (2026-07-20) when the palette had reached four hand-synced homes.
object DesignLang {

  type Hex = String

  case class Color(acr: String, css: String, hex: Hex)

  // ---------- the palette: ONE home for every value ----------
  val hio  = Color("HIO",  "hot-iron-orange",      "#ee582b")
  val chio = Color("CHIO", "chio-light-blue",      "#11a7d4")
  val vro  = Color("VRO",  "vivid-red-orange",     "#E22200") // #FA4616→#EE2400→#E22200 (BR 2026-07-20): redder + darker, ~3.7/3.6 on bone-white/TIP
  val cvro = Color("CVRO", "cvro-bright-blue",     "#05b9e9")
  val tb   = Color("TB",   "temper-blue",          "#095c75")
  val tip  = Color("TIP",  "tempered-iron-purple", "#17193f")
  val ctip = Color("CTIP", "ctip-bone-white",      "#e8e6c0")
  val acg  = Color("ACG",  "anvil-coal-graphite",  "#322b25")
  val cacg = Color("CACG", "cacg-cold-gray",       "#cdd4da")
  val ash  = Color("ASH",  "coal-ash",             "#7d6e5f") // mid-tone between ACG and CACG (BR 2026-07-20): garments/silhouettes on dark; the ash that banks the ember
  val npp  = Color("NPP",  "neon-pink-purple",     "#c724b1")
  val vbg  = Color("VBG",  "vivid-bright-green",   "#38db4e")

  val palette: Vector[Color] = Vector(hio, vro, chio, cvro, tb, tip, ctip, acg, cacg, ash, npp, vbg)

  // logo spec, frozen by BR 2026-07-20
  val logoWeight  = 700
  val logoGsScale = 1.35
  // VRO fine-tune neighbors (VRO settled to #E22200 2026-07-20; these stay in the lab for comparison)
  val vroCandidates: Vector[Hex] = Vector("#EE2400", "#D81F00")

  // ---------- WCAG 2.1 ----------
  def channel(v: Int): Double =
    val c = v / 255.0
    if c <= 0.04045 then c / 12.92 else math.pow((c + 0.055) / 1.055, 2.4)

  def luminance(hex: Hex): Double =
    val h = hex.stripPrefix("#")
    0.2126 * channel(Integer.parseInt(h.substring(0, 2), 16))
      + 0.7152 * channel(Integer.parseInt(h.substring(2, 4), 16))
      + 0.0722 * channel(Integer.parseInt(h.substring(4, 6), 16))

  def ratio(fg: Hex, bg: Hex): Double =
    val (l1, l2) = (luminance(fg) max luminance(bg), luminance(fg) min luminance(bg))
    (l1 + 0.05) / (l2 + 0.05)

  def badge(r: Double): String =
    if r >= 7.0 then "AAA" else if r >= 4.5 then "AA" else if r >= 3.0 then "AA-large" else "fail"

  val surfaces: Vector[(String, Hex)] =
    Vector("ACG" -> acg.hex, "TIP" -> tip.hex, "CTIP" -> ctip.hex, "CACG" -> cacg.hex, "white" -> "#ffffff")

  def contrastTable: String =
    val header = "| text color \\ background | " + surfaces.map(_._1).mkString(" | ") + " |"
    val sep    = "|---|" + surfaces.map(_ => "---|").mkString
    val rows = palette.map { c =>
      val cells = surfaces.map { (_, bg) =>
        if c.hex.equalsIgnoreCase(bg) then "-" else f"${ratio(c.hex, bg)}%.2f ${badge(ratio(c.hex, bg))}"
      }
      s"| ${c.acr} ${c.css} `${c.hex}` | " + cells.mkString(" | ") + " |"
    }
    (header +: sep +: rows).mkString("\n")

  val generatedNote =
    "<!-- GENERATED by DesignLang.scala - DO NOT EDIT THIS FILE. Edit DesignLang.scala and re-run:\n" +
    "     scala-cli run media/design-language/DesignLang.scala -->"

  // ---------- README.md ----------
  def readme: String =
    s"""$generatedNote
       |# genscalator's design language
       |
       |*GENERATED by [`DesignLang.scala`](DesignLang.scala) — the single point of truth. No edits
       |here, please: edit the Scala file and re-run it (`scala-cli run media/design-language/DesignLang.scala`).*
       |
       |Theme: blacksmith, forging, metallurgy and iron
       |
       |## Colors
       |
       |```css
       |--${hio.css}: ${hio.hex}; /* sampled from axe-2.jpg */
       |--${vro.css}: ${vro.hex};  /*  https://colorcodes.io/orange/red-orange-color-codes/ */
       |--${chio.css}: ${chio.hex};
       |--${cvro.css}: ${cvro.hex};
       |--${tb.css}: ${tb.hex}; /* link/accent blue for LIGHT surfaces; tempering blue, sv. blåanlöpning */
       |
       |--${tip.css}: ${tip.hex}; /* Tempered Iron Purple */
       |--${ctip.css}: ${ctip.hex};
       |
       |--${acg.css}: ${acg.hex}; /* anvil coal graphite */
       |--${cacg.css}: ${cacg.hex}; /* complement to anvil coal graphite */
       |--${ash.css}: ${ash.hex}; /* mid-tone coal ash: garments/silhouettes on dark grounds */
       |
       |--${npp.css}: ${npp.hex}; /* signal pair, base */
       |--${vbg.css}: ${vbg.hex}; /* complementary of neon-pink-purple */
       |```
       |
       |### Hot Iron Orange (HIO) ${hio.hex}
       |
       |hot-iron-orange, sampled from axe-2.jpg. Glowing iron at bright-orange working heat, roughly 900-950°C (about 1650-1750°F) *(approximate, read off the forge glow scale; verify against the temp-color chart in References before publishing)*
       |  * https://codeberg.org/bjornregnell/genscalator/src/branch/main/media/img/axe-2.jpg
       |
       |#### Complementary color of HIO: ${chio.hex}
       |
       |### Vivid Red Orange (VRO) ${vro.hex}
       |
       |  * https://sv.wikipedia.org/wiki/Smide#Gl%C3%B6dgning
       |
       |*(Updated 2026-07-20, twice: #FA4616 → #EE2400 → ${vro.hex} — redder (hue ≈9° vs HIO's ≈14°, so the
       |pair separates by hue, not just lightness) and darker for the LIGHT theme where VRO sits on
       |bone-white: now ≈3.7 on CTIP and ≈3.6 on TIP, symmetric comfort on both grounds. Fine-tune
       |neighbors ${vroCandidates.mkString(", ")} render as wordmarks on BOTH grounds in [logo-lab-GENERATED.html](logo-lab-GENERATED.html).)*
       |
       |#### Complementary color of VRO ${cvro.hex}
       |
       |### Temper Blue (TB): ${tb.hex}
       |
       |Tempering blue: steel tempered at around 300°C turns blue (sv. *blåanlöpning*) — the same oxide
       |color chart that gives TIP its purple, one step hotter. Derived 2026-07-20 by darkening the CHIO
       |hue until it clears WCAG AA on ALL light surfaces (white ${f"${ratio(tb.hex, "#ffffff")}%.2f"}, bone-white ${f"${ratio(tb.hex, ctip.hex)}%.2f"}, cold-gray ${f"${ratio(tb.hex, cacg.hex)}%.2f"}) —
       |the light-surface link/accent blue. On dark surfaces use CHIO/CVRO instead (TB fails there); no
       |single blue can serve both, so the blues come as a pair like the glow oranges vs the tempered darks.
       |Decorative exception (BR 2026-07-20): hairlines/rules on DARK may use TB deliberately — quiet by
       |design (2.24 on TIP), e.g. the index DARK theme's h1 seam under a hot-iron heading (the rule:
       |heading and its line must differ in color; light theme pairs a TIP heading with the hot-iron
       |line instead). Visible dark-surface accents remain CHIO/CVRO.
       |  * https://en.wikipedia.org/wiki/Tempering_(metallurgy)#/media/File:Tempering_colors_in_steel.jpg
       |  * https://sv.wikipedia.org/wiki/Anl%C3%B6pning
       |
       |### Tempered Iron Purple (TIP) ${tip.hex}
       |
       |Tempered iron at 282°C (540°F)
       |  * https://sv.wikipedia.org/wiki/Anl%C3%B6pning#/media/Fil:Tempering_standards_used_in_blacksmithing.JPG
       |  * https://en.wikipedia.org/wiki/Tempering_(metallurgy)#/media/File:Tempering_colors_in_steel.jpg
       |
       |#### Complementary color of TIP: ${ctip.hex}
       |
       |### Anvil Coal Graphite (ACG): ${acg.hex}
       |
       |A dark coal-stained cast anvil gray/brown sampled from axe-3
       |  * https://codeberg.org/bjornregnell/genscalator/src/branch/main/media/img/axe-3.jpg
       |
       |#### Complementary color of ACG: ${cacg.hex}

### Coal Ash (ASH): ${ash.hex}

The ash raked over the coals — the very act that banks the warp ember overnight. A mid-tone warm
gray between ACG and CACG, added 2026-07-20 when the mascots' graphite garments melted into the
dark TIP ground (ACG on TIP is only ${f"${ratio(acg.hex, tip.hex)}%.2f"}) while cold-gray would glow like bare metal
(${f"${ratio(cacg.hex, tip.hex)}%.2f"}). ASH sits in the working window: ${f"${ratio(ash.hex, tip.hex)}%.2f"} on TIP, ${f"${ratio(ash.hex, acg.hex)}%.2f"} against ACG beside it,
${f"${ratio(ash.hex, ctip.hex)}%.2f"} on bone-white. Role: garments, silhouette mid-tones, muted furniture on dark grounds.
       |
       |### Neon Pink Purple (NPP): ${npp.hex}
       |
       |The SIGNAL pair, base color — state semantics (chips, statusline, alerts) rather than material
       |iron-and-fire. Measured facts (see the contrast table): the one accent that is AA as TEXT on
       |white (${f"${ratio(npp.hex, "#ffffff")}%.2f"}); on dark it is large-text-only (TIP ${f"${ratio(npp.hex, tip.hex)}%.2f"}) and fails on graphite; as a chip
       |BACKGROUND its text must be white (${f"${ratio("#ffffff", npp.hex)}%.2f"}) — TIP or bone text stay below AA at chip sizes.
       |
       |#### Complementary color of NPP: ${vbg.hex} (Vivid Bright Green, VBG)
       |
       |Pure dark-surface signal: AAA-class on the tempered darks (TIP ${f"${ratio(vbg.hex, tip.hex)}%.2f"}, ACG ${f"${ratio(vbg.hex, acg.hex)}%.2f"}), fails on all
       |light surfaces — the glow-orange profile, in green. Natural role: the SmartZone/healthy chip on
       |dark, with TIP text. Smithy hook if wanted: copper burns green in the forge.
       |
       |### References:
       |  * https://colorcodes.io/
       |  * https://www.scribd.com/document/410753432/Steel-Temp-Color-Chart
       |  * https://rgbcolorpicker.com/complementary
       |
       |## Contrast (WCAG 2.1)
       |
       |Computed by DesignLang.scala from the palette above at generation time — always in sync.
       |Ratio then WCAG 2.1 verdict per cell.
       |
       |@CONTRAST-TABLE@
       |
       |Legend: AAA >= 7.0 · AA >= 4.5 (normal text) · AA-large >= 3.0 (large text/UI) · fail < 3.0 (WCAG 2.1).
       |
       |Reading of the table: **body text = bone-white or cold-gray on tempered purple or graphite** (all
       |four pairings are AAA both ways, so dark-on-light works equally well inverted); **the glow oranges
       |are accent/heading colors** — fine large on dark (AA on TIP, AA-large on ACG), never body text on
       |the light surfaces; **the complementary blues live on dark backgrounds only** (CVRO on TIP is even
       |AAA) and fail on white — which is why **temper blue** exists: the darker sibling that is AA-or-better
       |on all three light surfaces (and fails on dark; the blues are a pair, one per surface family).
       |
       |## Fonts
       |
       |* Fira Code (retina, regular, medium, bold)
       |* Fira Sans (regular, medium, bold)
       |
       |## Logo
       |
       |**Frozen (BR 2026-07-20): the wordmark.** All-lowercase `genscalator` in **Fira Code, weight $logoWeight**,
       |with the **g and s enlarged to ${logoGsScale}em** — the big letters spell out the `gs` command prefix, so the
       |mark teaches the vocabulary. Candidates: [logo-lab-GENERATED.html](logo-lab-GENERATED.html); in
       |context: [preview-GENERATED.html](preview-GENERATED.html).
       |
       |- **Canonical color mark (dark surfaces only):** smaller letters in HIO `${hio.hex}`, the enlarged
       |  g and s one step hotter in VRO `${vro.hex}` — a heat gradient inside the word. Backgrounds: TIP or
       |  ACG (both oranges fail contrast on the light surfaces, even at logo sizes — see the contrast table).
       |- **Light-surface variant (CANDIDATE, not yet ratified):** letters in TIP `${tip.hex}`, g and s in
       |  temper blue `${tb.hex}` — shown on the preview's light panel for judgment.
       |- **Small variant:** the enlarged `gs` pair extracted alone (favicon, statusline brand) — same
       |  colors, on an ACG rounded tile; sized specimens at 64/32/16 px in the logo lab.
       |
       |TODO for the SM155 logo family: settle the VRO push, outline the text to SVG paths (so the mark
       |stops depending on Fira being installed), export the color/black-white/big/small variants, and
       |ratify or replace the light-surface colors.
       |
       |## Further reading
       |
       |* Forging (en) == Smide (sv): [en](https://en.wikipedia.org/wiki/Forging) · [sv](https://sv.wikipedia.org/wiki/Smide)
       |* Tempering (en) == Anlöpning (sv): [en](https://en.wikipedia.org/wiki/Tempering_%28metallurgy%29) · [sv](https://sv.wikipedia.org/wiki/Anl%C3%B6pning)
       |* Annealing (en) == Glödgning (sv): [en](https://en.wikipedia.org/wiki/Annealing_%28materials_science%29) · [sv](https://sv.wikipedia.org/wiki/Gl%C3%B6dgning)
       |* Anvil (en) == Städ (sv): [en](https://en.wikipedia.org/wiki/Anvil) · [sv](https://sv.wikipedia.org/wiki/St%C3%A4d)
       |""".stripMargin.replace("@CONTRAST-TABLE@", contrastTable)
       // NB the table is substituted AFTER stripMargin: its rows start with `|`, which stripMargin
       // would otherwise eat as margin chars (live bug on first generation, 2026-07-20).

  // ---------- shared html bits ----------
  def cssVars: String = palette.map(c => s"    --${c.css}: ${c.hex};").mkString("\n")

  def wordmark(gsHex: Hex = ""): String =
    val style = if gsHex.isEmpty then "" else s""" style="color:$gsHex""""
    s"""<span class="gs"$style>g</span>en<span class="gs"$style>s</span>calator"""

  // ---------- preview-GENERATED.html ----------
  def preview: String =
    s"""<!DOCTYPE html>
       |<html lang="en">
       |<head>
       |<meta charset="utf-8">
       |<meta name="viewport" content="width=device-width, initial-scale=1">
       |<title>genscalator design language — preview</title>
       |$generatedNote
       |<style>
       |  :root {
       |$cssVars
       |    --sans: "Fira Sans", system-ui, sans-serif;
       |    --mono: "Fira Code", ui-monospace, monospace;
       |  }
       |  * { box-sizing: border-box; margin: 0; }
       |  body { font-family: var(--sans); background: #888; padding: 1rem; }
       |  .page { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; max-width: 1200px; margin: 0 auto; }
       |  @media (max-width: 800px) { .page { grid-template-columns: 1fr; } }
       |  .panel { padding: 2rem; border-radius: 8px; }
       |
       |  .dark { background: var(--${tip.css}); color: var(--${ctip.css}); }
       |  .dark .surface { background: var(--${acg.css}); }
       |  .dark h1, .dark h2 { color: var(--${hio.css}); }
       |  .dark .accent { color: var(--${vro.css}); }
       |  .dark a { color: var(--${cvro.css}); }
       |  .dark a:visited { color: var(--${chio.css}); }
       |  .dark .muted { color: var(--${cacg.css}); }
       |  .dark code, .dark pre { background: var(--${acg.css}); color: var(--${ctip.css}); }
       |  .dark .kw { color: var(--${hio.css}); }
       |  .dark .str { color: var(--${chio.css}); }
       |
       |  .light { background: var(--${ctip.css}); color: var(--${tip.css}); }
       |  .light .surface { background: var(--${cacg.css}); }
       |  .light h1, .light h2 { color: var(--${tip.css}); }
       |  .light h1 { border-bottom: 4px solid var(--${hio.css}); }
       |  .light .accent { color: var(--${acg.css}); }
       |  .light a { color: var(--${tb.css}); }
       |  .light a:visited { color: var(--${tip.css}); }
       |  .light .muted { color: var(--${acg.css}); }
       |  .light code, .light pre { background: var(--${tip.css}); color: var(--${ctip.css}); }
       |  .light .kw { color: var(--${hio.css}); }
       |  .light .str { color: var(--${cvro.css}); }
       |
       |  h1 { font-size: 1.6rem; margin-bottom: .25rem; padding-bottom: .25rem; }
       |  h2 { font-size: 1.1rem; margin: 1.2rem 0 .4rem; }
       |  p { line-height: 1.55; margin-bottom: .6rem; }
       |  pre { font-family: var(--mono); font-size: .85rem; padding: .8rem 1rem; border-radius: 6px; overflow-x: auto; margin: .5rem 0 1rem; }
       |  code { font-family: var(--mono); padding: .05rem .3rem; border-radius: 4px; }
       |  .surface { padding: 1rem; border-radius: 6px; margin: .8rem 0; }
       |  .chips { display: flex; gap: .5rem; flex-wrap: wrap; margin: .6rem 0 1rem; }
       |  .chip { font-family: var(--mono); font-size: .8rem; font-weight: bold; padding: .15rem .55rem; border-radius: 3px; }
       |  .chip.spend  { background: var(--${hio.css});  color: var(--${tip.css}); }
       |  .chip.smart  { background: var(--${vbg.css});  color: var(--${tip.css}); }
       |  .chip.cold   { background: var(--${chio.css}); color: var(--${tip.css}); }
       |  .chip.vigil  { background: var(--${vro.css});  color: var(--${tip.css}); } /* TIP text: bone drops to ~3.0 on the redder VRO */
       |  .chip.pink   { background: var(--${npp.css});  color: #ffffff; }
       |  .logo { font-family: var(--mono); font-weight: $logoWeight; font-size: 2.2rem; margin-bottom: 1rem; }
       |  .logo .gs { font-size: ${logoGsScale}em; }
       |  .dark .logo { color: var(--${hio.css}); }
       |  .dark .logo .gs { color: var(--${vro.css}); }
       |  .light .logo { color: var(--${tip.css}); }
       |  .light .logo .gs { color: var(--${tb.css}); }
       |  .swatches { display: grid; grid-template-columns: repeat(3, 1fr); gap: .5rem; margin-top: 1rem; }
       |  .sw { border-radius: 5px; padding: .5rem; font-family: var(--mono); font-size: .68rem; min-height: 3.2rem; }
       |</style>
       |</head>
       |<body>
       |<div class="page">
       |
       |  <section class="panel dark">
       |    <div class="logo">${wordmark()}</div>
       |    <h1>Forgy dark</h1>
       |    <p class="muted">tempered-iron purple ground · bone-white body · glow-orange headings</p>
       |    <div class="chips">
       |      <span class="chip spend">TokSpend</span><span class="chip smart">SmartZone</span>
       |      <span class="chip cold">ColdStart</span><span class="chip vigil">RotVigil</span><span class="chip pink">Racing</span>
       |    </div>
       |    <h2>Body and links</h2>
       |    <p>The exit banks the fire; the fresh agent blows the <span class="accent">warp ember</span>
       |       back into flame. Read the <a href="README.md">design language</a> — palette, contrast
       |       table and logo spec are all generated from one Scala source.</p>
       |    <div class="surface">
       |      <p>A raised surface in anvil-coal graphite. Inline code like <code>tt forge</code> sits on it.</p>
       |    </div>
       |    <h2>Code</h2>
       |    <pre><span class="kw">object</span> Forge:
       |  <span class="kw">val</span> ember = bank(fire)     <span class="str">// survives the warp</span>
       |  <span class="kw">def</span> morning = blow(ember)  <span class="str">// back into flame</span></pre>
       |    <div class="swatches">
       |      <div class="sw" style="background:${hio.hex};color:${tip.hex}">HIO ${hio.hex}</div>
       |      <div class="sw" style="background:${vro.hex};color:${ctip.hex}">VRO ${vro.hex}</div>
       |      <div class="sw" style="background:${cvro.hex};color:${tip.hex}">CVRO ${cvro.hex}</div>
       |      <div class="sw" style="background:${chio.hex};color:${tip.hex}">CHIO ${chio.hex}</div>
       |      <div class="sw" style="background:${vbg.hex};color:${tip.hex}">VBG ${vbg.hex}</div>
       |      <div class="sw" style="background:${npp.hex};color:#ffffff">NPP ${npp.hex}</div>
       |    </div>
       |  </section>
       |
       |  <section class="panel light">
       |    <div class="logo">${wordmark()}</div>
       |    <h1>Smither light</h1>
       |    <p class="muted">bone-white ground · tempered-purple body · hot-iron rule · temper-blue links</p>
       |    <div class="chips">
       |      <span class="chip spend">TokSpend</span><span class="chip smart">SmartZone</span>
       |      <span class="chip cold">ColdStart</span><span class="chip vigil">RotVigil</span><span class="chip pink">Racing</span>
       |    </div>
       |    <h2>Body and links</h2>
       |    <p>The exit banks the fire; the fresh agent blows the <span class="accent">warp ember</span>
       |       back into flame. Read the <a href="README.md">design language</a> — palette, contrast
       |       table and logo spec are all generated from one Scala source.</p>
       |    <div class="surface">
       |      <p>A raised surface in cold gray. Inline code like <code>tt forge</code> inverts to the dark pair.</p>
       |    </div>
       |    <h2>Code</h2>
       |    <pre><span class="kw">object</span> Forge:
       |  <span class="kw">val</span> ember = bank(fire)     <span class="str">// survives the warp</span>
       |  <span class="kw">def</span> morning = blow(ember)  <span class="str">// back into flame</span></pre>
       |    <div class="swatches">
       |      <div class="sw" style="background:${tb.hex};color:${ctip.hex}">TB ${tb.hex}</div>
       |      <div class="sw" style="background:${ctip.hex};color:${tip.hex}">CTIP ${ctip.hex}</div>
       |      <div class="sw" style="background:${cacg.hex};color:${acg.hex}">CACG ${cacg.hex}</div>
       |      <div class="sw" style="background:${hio.hex};color:${tip.hex}">HIO ${hio.hex}</div>
       |      <div class="sw" style="background:${tip.hex};color:${ctip.hex}">TIP ${tip.hex}</div>
       |      <div class="sw" style="background:${acg.hex};color:${cacg.hex}">ACG ${acg.hex}</div>
       |    </div>
       |  </section>
       |
       |</div>
       |</body>
       |</html>
       |""".stripMargin

  // ---------- index.html: the README rendered via the house ssg (Smither-light theme) ----------
  def indexTemplate: String =
    s"""<!DOCTYPE html>
       |<html lang="en">
       |<head>
       |<meta charset="utf-8">
       |<meta name="viewport" content="width=device-width, initial-scale=1">
       |<title>{{TITLE}}</title>
       |$generatedNote
       |<style>
       |  :root {
       |$cssVars
       |    --sans: "Fira Sans", system-ui, sans-serif;
       |    --mono: "Fira Code", ui-monospace, monospace;
       |  }
       |  * { box-sizing: border-box; }
       |  /* Smither light (default) — semantic vars flip per theme, palette vars never change */
       |  body {
       |    --bg: var(--${ctip.css}); --fg: var(--${tip.css}); --head: var(--${tip.css});
       |    --link: var(--${tb.css}); --visited: var(--${tip.css});
       |    --code-bg: var(--${tip.css}); --code-fg: var(--${ctip.css});
       |    --border: var(--${acg.css}); --th-bg: var(--${cacg.css});
       |    --logo-fg: var(--${tip.css}); --logo-gs: var(--${tb.css});
       |    --rule: var(--${hio.css}); /* TIP heading over the hot-iron line (heading and line must differ, BR) */
       |  }
       |  /* Forgy dark */
       |  body.dark {
       |    --bg: var(--${tip.css}); --fg: var(--${ctip.css}); --head: var(--${hio.css});
       |    --link: var(--${cvro.css}); --visited: var(--${chio.css});
       |    --code-bg: var(--${acg.css}); --code-fg: var(--${ctip.css});
       |    --border: var(--${cacg.css}); --th-bg: var(--${acg.css});
       |    --logo-fg: var(--${hio.css}); --logo-gs: var(--${vro.css});
       |    --rule: var(--${tb.css}); /* heading and its line must DIFFER (BR): HIO heading over a quiet temper-blue seam */
       |  }
       |  body { font-family: var(--sans); background: var(--bg); color: var(--fg);
       |         max-width: 60rem; margin: 0 auto; padding: 2rem 1.5rem 4rem; line-height: 1.55; }
       |  h1, h2, h3, h4 { color: var(--head); margin: 1.4em 0 .4em; }
       |  h1 { border-bottom: 4px solid var(--rule); padding-bottom: .25rem; }
       |  a { color: var(--link); }
       |  a:visited { color: var(--visited); }
       |  pre, code { font-family: var(--mono); }
       |  pre { background: var(--code-bg); color: var(--code-fg); padding: .8rem 1rem;
       |        border-radius: 6px; overflow-x: auto; }
       |  code { background: var(--code-bg); color: var(--code-fg); padding: .05rem .3rem; border-radius: 4px; }
       |  pre code { padding: 0; }
       |  table { border-collapse: collapse; margin: 1rem 0; }
       |  th, td { border: 1px solid var(--border); padding: .3rem .6rem; font-size: .9rem; }
       |  th { background: var(--th-bg); }
       |  .logo { font-family: var(--mono); font-weight: $logoWeight; font-size: 2.2rem;
       |          color: var(--logo-fg); margin-bottom: .2rem; }
       |  .logo .gs { font-size: ${logoGsScale}em; color: var(--logo-gs); }
       |  nav { font-family: var(--mono); font-size: .85rem; margin-bottom: 2rem; }
       |  #theme-toggle { position: fixed; top: 1rem; right: 1rem; font-family: var(--mono);
       |    font-size: .8rem; font-weight: bold; padding: .3rem .7rem; border-radius: 4px;
       |    border: 1px solid var(--border); background: var(--code-bg); color: var(--code-fg); cursor: pointer; }
       |</style>
       |</head>
       |<body>
       |<button id="theme-toggle">Forgy dark</button>
       |<script>
       |  (function () {
       |    var btn = document.getElementById('theme-toggle');
       |    function label() { btn.textContent = document.body.classList.contains('dark') ? 'Smither light' : 'Forgy dark'; }
       |    var saved = localStorage.getItem('gs-design-theme');
       |    if (saved === 'dark' || (saved === null && window.matchMedia('(prefers-color-scheme: dark)').matches))
       |      document.body.classList.add('dark');
       |    label();
       |    btn.addEventListener('click', function () {
       |      document.body.classList.toggle('dark');
       |      localStorage.setItem('gs-design-theme', document.body.classList.contains('dark') ? 'dark' : 'light');
       |      label();
       |    });
       |  })();
       |</script>
       |<div class="logo">${wordmark()}</div>
       |<nav><a href="preview-GENERATED.html">preview</a> · <a href="logo-lab-GENERATED.html">logo lab</a> ·
       |  <a href="mascot-lab-GENERATED.html">mascot lab</a> · <a href="DesignLang.scala">source of truth</a></nav>
       |{{CONTENT}}
       |</body>
       |</html>
       |""".stripMargin

  def index: String = Ssg.renderPage(readme, indexTemplate)

  // ---------- logo-lab-GENERATED.html ----------
  def logoLab: String =
    def markRow(cls: String) = s"""    <div class="mark big $cls">${wordmark()}</div>"""
    val gridRows = (for w <- Vector(500, 700); s <- Vector(120, 135, 150) yield (w, s))
    def rows(ws: Vector[(Int, Int)]) = ws.map((w, s) => markRow(s"w$w s$s")).mkString("\n")
    val candidateRows = vroCandidates.map(hex => s"""    <div class="mark big w$logoWeight s135">${wordmark(hex)}</div>""").mkString("\n")
    val candidateRowsLight = candidateRows
    def wordmarkLight = s"""<span class="gs" style="color:${tb.hex}">g</span>en<span class="gs" style="color:${tb.hex}">s</span>calator"""
    val lightVariantSection =
      s"""  <section class="panel light">
         |    <div class="label">Smither-light VARIANT (TIP letters, temper-blue gs) — the light-surface mark candidate: big / heading / inline + gs tile</div>
         |    <div class="mark big w$logoWeight s135" style="color:${tip.hex}">$wordmarkLight</div>
         |    <div class="mark mid w$logoWeight s135" style="color:${tip.hex}">$wordmarkLight</div>
         |    <div class="mark tiny w$logoWeight s135" style="color:${tip.hex}">$wordmarkLight</div>
         |    <div class="favrow">
         |      <div class="fav f64" style="background:${cacg.hex}"><span class="mark w$logoWeight" style="color:${tip.hex}"><span class="gs" style="color:${tb.hex}">g</span><span class="gs" style="color:${tb.hex}">s</span></span></div>
         |      <div class="fav f32" style="background:${cacg.hex}"><span class="mark w$logoWeight" style="color:${tip.hex}"><span class="gs" style="color:${tb.hex}">g</span><span class="gs" style="color:${tb.hex}">s</span></span></div>
         |    </div>
         |  </section>""".stripMargin
    s"""<!DOCTYPE html>
       |<html lang="en">
       |<head>
       |<meta charset="utf-8">
       |<meta name="viewport" content="width=device-width, initial-scale=1">
       |<title>genscalator logo lab</title>
       |$generatedNote
       |<style>
       |  :root {
       |$cssVars
       |    --mono: "Fira Code", "Fira Mono", ui-monospace, monospace;
       |  }
       |  * { box-sizing: border-box; margin: 0; }
       |  body { font-family: system-ui, sans-serif; background: #888; padding: 1rem; }
       |  .lab { max-width: 1100px; margin: 0 auto; display: grid; gap: 1rem; }
       |  .panel { border-radius: 8px; padding: 1.5rem 2rem; }
       |  .tip { background: var(--${tip.css}); } .acg { background: var(--${acg.css}); } .light { background: var(--${ctip.css}); }
       |  .label { font-size: .75rem; color: #ccc; font-family: var(--mono); margin: 1.1rem 0 .2rem; }
       |  .light .label { color: #555; }
       |  .mark { font-family: var(--mono); color: var(--${hio.css}); }
       |  .mark .gs { color: var(--${vro.css}); }
       |  .w500 { font-weight: 500; } .w700 { font-weight: 700; }
       |  .s120 .gs { font-size: 1.20em; } .s135 .gs { font-size: 1.35em; } .s150 .gs { font-size: 1.50em; }
       |  .big { font-size: 3rem; } .mid { font-size: 1.6rem; } .tiny { font-size: .95rem; }
       |  .favrow { display: flex; gap: 1rem; align-items: center; margin-top: .4rem; }
       |  .fav { background: var(--${acg.css}); border-radius: 20%; display: grid; place-items: center; }
       |  .f64 { width: 64px; height: 64px; font-size: 30px; }
       |  .f32 { width: 32px; height: 32px; font-size: 15px; }
       |  .f16 { width: 16px; height: 16px; font-size: 8px; }
       |</style>
       |</head>
       |<body>
       |<div class="lab">
       |
       |  <section class="panel tip">
       |    <div class="label">weight 500 · gs 1.20 / 1.35 / 1.50 — on tempered-iron purple (frozen pick: w$logoWeight s${(logoGsScale * 100).toInt})</div>
       |${rows(gridRows.take(3))}
       |    <div class="label">weight 700 · gs 1.20 / 1.35 / 1.50</div>
       |${rows(gridRows.drop(3))}
       |  </section>
       |
       |  <section class="panel acg">
       |    <div class="label">same six on anvil-coal graphite</div>
       |${rows(gridRows)}
       |  </section>
       |
       |  <section class="panel tip">
       |    <div class="label">smaller sizes (frozen spec): heading and inline</div>
       |    <div class="mark mid w$logoWeight s135">${wordmark()}</div>
       |    <div class="mark tiny w$logoWeight s135">${wordmark()}</div>
       |    <div class="label">the small variant: gs extracted (favicon / statusline brand)</div>
       |    <div class="favrow">
       |      <div class="fav f64"><span class="mark w$logoWeight"><span class="gs">g</span><span class="gs">s</span></span></div>
       |      <div class="fav f32"><span class="mark w$logoWeight"><span class="gs">g</span><span class="gs">s</span></span></div>
       |      <div class="fav f16"><span class="mark w$logoWeight"><span class="gs">g</span><span class="gs">s</span></span></div>
       |    </div>
       |  </section>
       |
       |  <section class="panel tip">
       |    <div class="label">VRO candidates for the hot gs (frozen weight/scale): current ${vro.hex} then ${vroCandidates.mkString(" · ")}</div>
       |    <div class="mark big w$logoWeight s135">${wordmark()}</div>
       |$candidateRows
       |  </section>
       |
       |  <section class="panel light">
       |    <div class="label">VRO on BONE-WHITE (its light-theme accent ground): current ${vro.hex} then ${vroCandidates.mkString(" · ")}
       |      — judge the gs redness where the light theme actually uses it (smaller HIO letters stay
       |      washed here on purpose: the full color mark remains DARK-surface; light pages use the
       |      TIP+temper-blue variant)</div>
       |    <div class="mark big w$logoWeight s135">${wordmark()}</div>
       |$candidateRowsLight
       |  </section>
       |
       |@LIGHT-VARIANT-SECTION@
       |
       |</div>
       |</body>
       |</html>
       |""".stripMargin.replace("@LIGHT-VARIANT-SECTION@", lightVariantSection)
       // (substituted after stripMargin, same trick as the contrast table)

  // ---------- mascot-lab-GENERATED.html: Forgy & Smither, v1 geometric takes ----------
  // Forgy = the FEMALE twin (BR 2026-07-20), the hot impulsive one: hammer, HIO/VRO accents, Forgy dark.
  // Smither = the male twin, calm + methodical: TONGS (= human control, holding the hot iron safely),
  // TIP/temper-blue accents, Smither light. Tableau: Forgy left, anvil with the axe center, Smither right.
  // All fills interpolate the palette, so mascots re-skin when the palette moves. Charmingly primitive v1.

  def forgySvg: String =
    s"""<g>
       |  <ellipse cx="144" cy="66" rx="12" ry="26" transform="rotate(22 144 66)" fill="${vro.hex}"/>
       |  <circle cx="100" cy="80" r="34" fill="${ctip.hex}"/>
       |  <path d="M66 80 A34 34 0 0 1 134 80 L134 74 Q118 60 112 66 Q100 48 78 58 Q68 64 66 74 Z" fill="${vro.hex}"/>
       |  <circle cx="88" cy="90" r="4" fill="${tip.hex}"/>
       |  <circle cx="112" cy="90" r="4" fill="${tip.hex}"/>
       |  <path d="M88 102 Q100 112 112 102" stroke="${tip.hex}" stroke-width="3" fill="none" stroke-linecap="round"/>
       |  <path d="M70 114 L130 114 L146 210 L54 210 Z" fill="${hio.hex}"/>
       |  <path d="M84 130 L116 130 L124 200 L76 200 Z" fill="${ash.hex}"/>
       |  <line x1="70" y1="130" x2="36" y2="104" stroke="${hio.hex}" stroke-width="12" stroke-linecap="round"/>
       |  <line x1="36" y1="104" x2="22" y2="64" stroke="${acg.hex}" stroke-width="7" stroke-linecap="round"/>
       |  <rect x="4" y="50" width="38" height="17" rx="3" fill="${acg.hex}"/>
       |  <circle cx="52" cy="56" r="6" fill="${vro.hex}" opacity="0.25"/>
       |  <circle cx="52" cy="58" r="3" fill="${vro.hex}"/>
       |  <circle cx="60" cy="42" r="2.5" fill="${vro.hex}"/>
       |  <circle cx="44" cy="38" r="2" fill="${hio.hex}"/>
       |  <line x1="130" y1="130" x2="158" y2="168" stroke="${hio.hex}" stroke-width="12" stroke-linecap="round"/>
       |  <rect x="82" y="210" width="12" height="28" fill="${ash.hex}"/>
       |  <rect x="106" y="210" width="12" height="28" fill="${ash.hex}"/>
       |  <rect x="76" y="236" width="22" height="8" rx="3" fill="${acg.hex}"/>
       |  <rect x="102" y="236" width="22" height="8" rx="3" fill="${acg.hex}"/>
       |</g>""".stripMargin

  def smitherSvg: String =
    s"""<g>
       |  <circle cx="100" cy="80" r="34" fill="${ctip.hex}"/>
       |  <path d="M68 72 A32 32 0 0 1 132 72 Z" fill="${ash.hex}"/>
       |  <circle cx="88" cy="90" r="8" stroke="${tb.hex}" stroke-width="2.5" fill="none"/>
       |  <circle cx="112" cy="90" r="8" stroke="${tb.hex}" stroke-width="2.5" fill="none"/>
       |  <line x1="96" y1="90" x2="104" y2="90" stroke="${tb.hex}" stroke-width="2.5"/>
       |  <circle cx="88" cy="90" r="3" fill="${tip.hex}"/>
       |  <circle cx="112" cy="90" r="3" fill="${tip.hex}"/>
       |  <line x1="90" y1="106" x2="110" y2="106" stroke="${tip.hex}" stroke-width="3" stroke-linecap="round"/>
       |  <path d="M70 114 L130 114 L140 210 L60 210 Z" fill="${tb.hex}"/>
       |  <rect x="66" y="158" width="68" height="10" fill="${ash.hex}"/>
       |  <line x1="70" y1="132" x2="38" y2="158" stroke="${tb.hex}" stroke-width="12" stroke-linecap="round"/>
       |  <line x1="38" y1="158" x2="10" y2="148" stroke="${acg.hex}" stroke-width="5" stroke-linecap="round"/>
       |  <line x1="38" y1="158" x2="12" y2="170" stroke="${acg.hex}" stroke-width="5" stroke-linecap="round"/>
       |  <circle cx="38" cy="158" r="5" fill="${acg.hex}"/>
       |  <circle cx="6" cy="156" r="11" fill="${hio.hex}" opacity="0.22"/>
       |  <rect x="0" y="152" width="13" height="9" rx="2" fill="${hio.hex}"/>
       |  <line x1="130" y1="132" x2="156" y2="172" stroke="${tb.hex}" stroke-width="12" stroke-linecap="round"/>
       |  <rect x="82" y="210" width="12" height="28" fill="${ash.hex}"/>
       |  <rect x="106" y="210" width="12" height="28" fill="${ash.hex}"/>
       |  <rect x="76" y="236" width="22" height="8" rx="3" fill="${acg.hex}"/>
       |  <rect x="102" y="236" width="22" height="8" rx="3" fill="${acg.hex}"/>
       |</g>""".stripMargin

  def anvilAxeSvg: String =
    s"""<g>
       |  <line x1="52" y1="38" x2="132" y2="30" stroke="${acg.hex}" stroke-width="6" stroke-linecap="round"/>
       |  <path d="M30 18 L54 25 L52 44 L26 40 Q16 29 30 18 Z" fill="${cacg.hex}"/>
       |  <path d="M26 40 Q16 29 30 18" stroke="${hio.hex}" stroke-width="3" fill="none" stroke-linecap="round"/>
       |  <rect x="20" y="44" width="120" height="18" rx="4" fill="${ash.hex}" stroke="${acg.hex}" stroke-width="3"/>
       |  <path d="M20 44 L20 62 L0 53 Z" fill="${ash.hex}" stroke="${acg.hex}" stroke-width="3"/>
       |  <rect x="62" y="62" width="36" height="16" fill="${ash.hex}" stroke="${acg.hex}" stroke-width="3"/>
       |  <rect x="48" y="78" width="64" height="14" rx="3" fill="${ash.hex}" stroke="${acg.hex}" stroke-width="3"/>
       |</g>""".stripMargin

  def mascotLab: String =
    def tableau =
      s"""<svg viewBox="0 0 640 300" width="640" role="img" aria-label="Forgy and Smither at the anvil">
         |  <line x1="10" y1="283" x2="630" y2="283" stroke="${cacg.hex}" stroke-width="2" opacity="0.5"/>
         |  <g transform="translate(215,39) scale(-1,1)">$forgySvg</g>
         |  <g transform="translate(240,191)">$anvilAxeSvg</g>
         |  <g transform="translate(425,39)">$smitherSvg</g>
         |</svg>""".stripMargin
    def solo(svg: String, label: String) =
      s"""<figure><svg viewBox="0 0 200 260" width="180" role="img" aria-label="$label">$svg</svg><figcaption>$label</figcaption></figure>"""
    s"""<!DOCTYPE html>
       |<html lang="en">
       |<head>
       |<meta charset="utf-8">
       |<meta name="viewport" content="width=device-width, initial-scale=1">
       |<title>genscalator mascot lab — Forgy &amp; Smither</title>
       |$generatedNote
       |<style>
       |  * { box-sizing: border-box; margin: 0; }
       |  body { font-family: "Fira Sans", system-ui, sans-serif; background: #888; padding: 1rem; }
       |  .lab { max-width: 1100px; margin: 0 auto; display: grid; gap: 1rem; }
       |  .panel { border-radius: 8px; padding: 1.5rem 2rem; }
       |  .tip { background: ${tip.hex}; } .light { background: ${ctip.hex}; }
       |  .label { font-size: .75rem; color: #ccc; font-family: "Fira Code", monospace; margin: 0 0 .6rem; }
       |  .light .label { color: #555; }
       |  .row { display: flex; gap: 2rem; align-items: flex-end; flex-wrap: wrap; }
       |  figure { text-align: center; }
       |  figcaption { font-family: "Fira Code", monospace; font-size: .8rem; color: #999; margin-top: .3rem; }
       |</style>
       |</head>
       |<body>
       |<div class="lab">
       |  <section class="panel tip">
       |    <div class="label">v1 geometric takes — Forgy (female, hammer, the hot one) · Smither (male, tongs = human control, holding a glowing ember) — iterate in DesignLang.scala</div>
       |    <div class="row">
       |      ${solo(forgySvg, "Forgy")}
       |      ${solo(smitherSvg, "Smither")}
       |    </div>
       |  </section>
       |  <section class="panel tip">
       |    <div class="label">the tableau: Forgy · anvil with the freshly-forged axe (HIO edge-glow) · Smither</div>
       |    $tableau
       |  </section>
       |  <section class="panel light">
       |    <div class="label">same tableau on Smither light</div>
       |    $tableau
       |  </section>
       |</div>
       |</body>
       |</html>
       |""".stripMargin
}

@main def generateDesignLanguage(outDir: String*): Unit =
  import java.nio.file.{Files, Path}
  val dir = outDir.headOption.map(Path.of(_)).getOrElse {
    val next = Path.of("media", "design-language") // run from the repo root
    if Files.isDirectory(next) then next else Path.of(".") // or from this dir
  }
  val outputs = Vector(
    "README.md"                 -> DesignLang.readme,
    "index.html"                -> DesignLang.index,
    "preview-GENERATED.html"    -> DesignLang.preview,
    "logo-lab-GENERATED.html"   -> DesignLang.logoLab,
    "mascot-lab-GENERATED.html" -> DesignLang.mascotLab,
  )
  for (name, content) <- outputs do
    Files.writeString(dir.resolve(name), content)
    println(s"DesignLang: wrote $name (${content.linesIterator.size} lines)")
