//> using scala 3.8.4
//> using file ../../tools/lib.scala
//> using file ../../tools/mdparse.scala
//> using file ../../tools/ssg.scala
// NB all three declared here: `using file` does NOT chain, so ssg's own file-directives are
// inert when ssg.scala is included this way. Two @mains in the unit (ssg's + ours) ⇒ run with:
//   scala-cli run . --main-class generateDesignLanguage
// DesignLang — THE single point of truth for the genscalator design language (SM155/T8).
// Effectful driver by design (visible effects only at the end): generates README.md,
// index.html (the README rendered through the house Ssg.renderPage — one parser, one more
// consumer), preview-GENERATED.html and logo-lab-GENERATED.html next to this file (or into
// the dir given as the single optional arg). Everything else in this folder is OUTPUT — edit HERE, re-run:
//   scala-cli run media/design-language/DesignLang.scala
// Grew from contrast.scala (2026-07-20) when the palette had reached four hand-synced homes.
object DesignLang {

  type Hex = String

  case class Color(acr: String, css: String, hex: Hex)

  // ---------- the palette: ONE home for every value ----------
  val hio  = Color("HIO",  "hot-iron-orange",      "#ee582b")
  val chio = Color("CHIO", "chio-light-blue",      "#11a7d4")
  val vro  = Color("VRO",  "vivid-red-orange",     "#E22200") // #FA4616→#EE2400→#E22200 (BR 2026-07-20): redder + darker, ~3.7/3.6 on bone-white/TIP
  val cvro = Color("CVRO", "cvro-bright-blue",     "#05b9e9")
  val tb   = Color("TB",   "temper-blue",          "#095c75")
  val tip  = Color("TIP",  "tempered-iron-purple", "#17193f")
  val ctip = Color("CTIP", "ctip-bone-white",      "#e8e6c0")
  val acg  = Color("ACG",  "anvil-coal-graphite",  "#322b25")
  val cacg = Color("CACG", "cacg-cold-gray",       "#cdd4da")
  val ash  = Color("ASH",  "coal-ash",             "#7d6e5f") // mid-tone between ACG and CACG (BR 2026-07-20): garments/silhouettes on dark; the ash that banks the ember
  val npp  = Color("NPP",  "neon-pink-purple",     "#c724b1")
  val vbg  = Color("VBG",  "vivid-bright-green",   "#38db4e")

  val palette: Vector[Color] = Vector(hio, vro, chio, cvro, tb, tip, ctip, acg, cacg, ash, npp, vbg)

  // Theme SURFACE TOKENS (BR 2026-07-20), deliberately NOT palette members: the forge palette
  // tells the brand story; these two near-neutrals only carry the Calm reading pair, each
  // doubling as the other's text color (DNG text on DLW ground and vice versa).
  val dng = Color("DNG", "dark-night-graphite", "#14161a") // Calm dark ground, Calm light text
  val dlw = Color("DLW", "day-light-white",     "#fafafa") // Calm light ground, Calm dark text
  val surfaceTokens: Vector[Color] = Vector(dng, dlw)

  // logo spec, frozen by BR 2026-07-20
  val logoWeight  = 700
  val logoGsScale = 1.35
  // VRO fine-tune neighbors (VRO settled to #E22200 2026-07-20; these stay in the lab for comparison)
  val vroCandidates: Vector[Hex] = Vector("#EE2400", "#D81F00")

  // ---------- WCAG 2.1 ----------
  def channel(v: Int): Double =
    val c = v / 255.0
    if c <= 0.04045 then c / 12.92 else math.pow((c + 0.055) / 1.055, 2.4)

  def luminance(hex: Hex): Double =
    val h = hex.stripPrefix("#")
    0.2126 * channel(Integer.parseInt(h.substring(0, 2), 16))
      + 0.7152 * channel(Integer.parseInt(h.substring(2, 4), 16))
      + 0.0722 * channel(Integer.parseInt(h.substring(4, 6), 16))

  def ratio(fg: Hex, bg: Hex): Double =
    val (l1, l2) = (luminance(fg) max luminance(bg), luminance(fg) min luminance(bg))
    (l1 + 0.05) / (l2 + 0.05)

  def badge(r: Double): String =
    if r >= 7.0 then "AAA" else if r >= 4.5 then "AA" else if r >= 3.0 then "AA-large" else "fail"

  val surfaces: Vector[(String, Hex)] =
    Vector("ACG" -> acg.hex, "TIP" -> tip.hex, "DNG" -> dng.hex, "CTIP" -> ctip.hex, "CACG" -> cacg.hex, "DLW" -> dlw.hex, "white" -> "#ffffff")

  def contrastTable: String =
    val header = "| text color \\ background | " + surfaces.map(_._1).mkString(" | ") + " |"
    val sep    = "|---|" + surfaces.map(_ => "---|").mkString
    val rows = palette.map { c =>
      val cells = surfaces.map { (_, bg) =>
        if c.hex.equalsIgnoreCase(bg) then "-" else f"${ratio(c.hex, bg)}%.2f ${badge(ratio(c.hex, bg))}"
      }
      s"| ${c.acr} ${c.css} `${c.hex}` | " + cells.mkString(" | ") + " |"
    }
    (header +: sep +: rows).mkString("\n")

  val generatedNote =
    "<!-- GENERATED by DesignLang.scala - DO NOT EDIT THIS FILE. Edit DesignLang.scala and re-run:\n" +
    "     scala-cli run media/design-language/DesignLang.scala -->"

  // ---------- README.md ----------
  def readme: String =
    s"""$generatedNote
       |# genscalator's design language
       |
       |*GENERATED by [`DesignLang.scala`](DesignLang.scala) — the single point of truth. No edits
       |here, please: edit the Scala file and re-run it (`scala-cli run media/design-language/DesignLang.scala`).*
       |
       |Theme: blacksmith, forging, metallurgy and iron
       |
       |## Colors
       |
       |```css
       |--${hio.css}: ${hio.hex}; /* sampled from axe-2.jpg */
       |--${vro.css}: ${vro.hex};  /*  https://colorcodes.io/orange/red-orange-color-codes/ */
       |--${chio.css}: ${chio.hex};
       |--${cvro.css}: ${cvro.hex};
       |--${tb.css}: ${tb.hex}; /* link/accent blue for LIGHT surfaces; tempering blue, sv. blåanlöpning */
       |
       |--${tip.css}: ${tip.hex}; /* Tempered Iron Purple */
       |--${ctip.css}: ${ctip.hex};
       |
       |--${acg.css}: ${acg.hex}; /* anvil coal graphite */
       |--${cacg.css}: ${cacg.hex}; /* complement to anvil coal graphite */
       |--${ash.css}: ${ash.hex}; /* mid-tone coal ash: garments/silhouettes on dark grounds */
       |
       |--${npp.css}: ${npp.hex}; /* signal pair, base */
       |--${vbg.css}: ${vbg.hex}; /* complementary of neon-pink-purple */
       |```
       |
       |### Hot Iron Orange (HIO) ${hio.hex}
       |
       |hot-iron-orange, sampled from axe-2.jpg. Glowing iron at bright-orange working heat, roughly 900-950°C (about 1650-1750°F) *(approximate, read off the forge glow scale; verify against the temp-color chart in References before publishing)*
       |  * https://github.com/bjornregnell/genscalator/blob/main/media/img/axe-2.jpg
       |
       |#### Complementary color of HIO: ${chio.hex}
       |
       |### Vivid Red Orange (VRO) ${vro.hex}
       |
       |  * https://sv.wikipedia.org/wiki/Smide#Gl%C3%B6dgning
       |
       |*(Updated 2026-07-20, twice: #FA4616 → #EE2400 → ${vro.hex} — redder (hue ≈9° vs HIO's ≈14°, so the
       |pair separates by hue, not just lightness) and darker for the LIGHT theme where VRO sits on
       |bone-white: now ≈3.7 on CTIP and ≈3.6 on TIP, symmetric comfort on both grounds. Fine-tune
       |neighbors ${vroCandidates.mkString(", ")} render as wordmarks on BOTH grounds in [logo-lab-GENERATED.html](logo-lab-GENERATED.html).)*
       |
       |#### Complementary color of VRO ${cvro.hex}
       |
       |### Temper Blue (TB): ${tb.hex}
       |
       |Tempering blue: steel tempered at around 300°C turns blue (sv. *blåanlöpning*) — the same oxide
       |color chart that gives TIP its purple, one step hotter. Derived 2026-07-20 by darkening the CHIO
       |hue until it clears WCAG AA on ALL light surfaces (white ${f"${ratio(tb.hex, "#ffffff")}%.2f"}, bone-white ${f"${ratio(tb.hex, ctip.hex)}%.2f"}, cold-gray ${f"${ratio(tb.hex, cacg.hex)}%.2f"}) —
       |the light-surface link/accent blue. On dark surfaces use CHIO/CVRO instead (TB fails there); no
       |single blue can serve both, so the blues come as a pair like the glow oranges vs the tempered darks.
       |Decorative exception (BR 2026-07-20): hairlines/rules on DARK may use TB deliberately — quiet by
       |design (2.24 on TIP), e.g. the index DARK theme's h1 seam under a hot-iron heading (the rule:
       |heading and its line must differ in color; light theme pairs a TIP heading with the hot-iron
       |line instead). Visible dark-surface accents remain CHIO/CVRO.
       |  * https://en.wikipedia.org/wiki/Tempering_(metallurgy)#/media/File:Tempering_colors_in_steel.jpg
       |  * https://sv.wikipedia.org/wiki/Anl%C3%B6pning
       |
       |### Tempered Iron Purple (TIP) ${tip.hex}
       |
       |Tempered iron at 282°C (540°F)
       |  * https://sv.wikipedia.org/wiki/Anl%C3%B6pning#/media/Fil:Tempering_standards_used_in_blacksmithing.JPG
       |  * https://en.wikipedia.org/wiki/Tempering_(metallurgy)#/media/File:Tempering_colors_in_steel.jpg
       |
       |#### Complementary color of TIP: ${ctip.hex}
       |
       |### Anvil Coal Graphite (ACG): ${acg.hex}
       |
       |A dark coal-stained cast anvil gray/brown sampled from axe-3
       |  * https://github.com/bjornregnell/genscalator/blob/main/media/img/axe-3.jpg
       |
       |#### Complementary color of ACG: ${cacg.hex}

### Coal Ash (ASH): ${ash.hex}

The ash raked over the coals — the very act that banks the warp ember overnight. A mid-tone warm
gray between ACG and CACG, added 2026-07-20 when the mascots' graphite garments melted into the
dark TIP ground (ACG on TIP is only ${f"${ratio(acg.hex, tip.hex)}%.2f"}) while cold-gray would glow like bare metal
(${f"${ratio(cacg.hex, tip.hex)}%.2f"}). ASH sits in the working window: ${f"${ratio(ash.hex, tip.hex)}%.2f"} on TIP, ${f"${ratio(ash.hex, acg.hex)}%.2f"} against ACG beside it,
${f"${ratio(ash.hex, ctip.hex)}%.2f"} on bone-white. Role: garments, silhouette mid-tones, muted furniture on dark grounds.
       |
       |### Neon Pink Purple (NPP): ${npp.hex}
       |
       |The SIGNAL pair, base color — state semantics (chips, statusline, alerts) rather than material
       |iron-and-fire. Measured facts (see the contrast table): the one accent that is AA as TEXT on
       |white (${f"${ratio(npp.hex, "#ffffff")}%.2f"}); on dark it is large-text-only (TIP ${f"${ratio(npp.hex, tip.hex)}%.2f"}) and fails on graphite; as a chip
       |BACKGROUND its text must be white (${f"${ratio("#ffffff", npp.hex)}%.2f"}) — TIP or bone text stay below AA at chip sizes.
       |
       |#### Complementary color of NPP: ${vbg.hex} (Vivid Bright Green, VBG)
       |
       |Pure dark-surface signal: AAA-class on the tempered darks (TIP ${f"${ratio(vbg.hex, tip.hex)}%.2f"}, ACG ${f"${ratio(vbg.hex, acg.hex)}%.2f"}), fails on all
       |light surfaces — the glow-orange profile, in green. Natural role: the SmartZone/healthy chip on
       |dark, with TIP text. Smithy hook if wanted: copper burns green in the forge.
       |
       |### References:
       |  * https://colorcodes.io/
       |  * https://www.scribd.com/document/410753432/Steel-Temp-Color-Chart
       |  * https://rgbcolorpicker.com/complementary
       |
       |## Contrast (WCAG 2.1)
       |
       |Computed by DesignLang.scala from the palette above at generation time — always in sync.
       |Ratio then WCAG 2.1 verdict per cell.
       |
       |@CONTRAST-TABLE@
       |
       |Legend: AAA >= 7.0 · AA >= 4.5 (normal text) · AA-large >= 3.0 (large text/UI) · fail < 3.0 (WCAG 2.1).
       |
       |Reading of the table: **body text = bone-white or cold-gray on tempered purple or graphite** (all
       |four pairings are AAA both ways, so dark-on-light works equally well inverted); **the glow oranges
       |are accent/heading colors** — fine large on dark (AA on TIP, AA-large on ACG), never body text on
       |the light surfaces; **the complementary blues live on dark backgrounds only** (CVRO on TIP is even
       |AAA) and fail on white — which is why **temper blue** exists: the darker sibling that is AA-or-better
       |on all three light surfaces (and fails on dark; the blues are a pair, one per surface family).
       |
       |## Themes
       |
       |Four themes plus Automatic, one dropdown (BR 2026-07-20): every page carries
       |`<select id="theme-select">`, filled and wired by `design.js` (or the blog template's inline
       |copy of the same generated script) from the same list that names the CSS variable-sets, and
       |applied as `data-theme` on `<html>`. The choice persists in `localStorage` (`gs-theme`).
       |**Automatic is the first-visit default: it follows the OS light/dark setting with the Calm
       |pair** and keeps following live OS changes; the brand-loud pair is an explicit pick.
       |
       || theme | ground | text | headings | links |
       ||---|---|---|---|---|
       || Forgy dark | TIP | CTIP | HIO | CVRO |
       || Smither light | CTIP | TIP | TIP over an HIO rule | TB |
       || Calm dark (Automatic + OS dark) | DNG | DLW | DLW | CHIO |
       || Calm light (Automatic + OS light) | DLW | DNG | DNG | TB |
       |
       |The Calm pair keeps the fonts, the logo and the chips but takes the brand colors out of text
       |and headings — the h1 rule turns coal-ash and links keep a single accent. Its grounds are two
       |theme SURFACE TOKENS, deliberately NOT palette members (the forge palette tells the brand
       |story; these near-neutrals only carry the calm reading pair, each doubling as the other's
       |text color — ${f"${ratio(dlw.hex, dng.hex)}%.2f"} both ways):
       |
       |```css
       |--${dng.css}: ${dng.hex}; /* DNG: Calm dark ground, Calm light text */
       |--${dlw.css}: ${dlw.hex}; /* DLW: Calm light ground, Calm dark text */
       |```
       |
       |Code blocks stay TIP-grounded in ALL four themes, so the one measured syntax-token color-set
       |serves every theme; both tokens also appear as columns in the contrast table above.
       |
       |## Fonts
       |
       |* Fira Code (retina, regular, medium, bold)
       |* Fira Sans (regular, medium, bold)
       |
       |## Logo
       |
       |**Frozen (BR 2026-07-20): the wordmark.** All-lowercase `genscalator` in **Fira Code, weight $logoWeight**,
       |with the **g and s enlarged to ${logoGsScale}em** — the big letters spell out the `gs` command prefix, so the
       |mark teaches the vocabulary. Candidates: [logo-lab-GENERATED.html](logo-lab-GENERATED.html); in
       |context: [preview-GENERATED.html](preview-GENERATED.html).
       |
       |- **Canonical color mark (dark surfaces only):** smaller letters in HIO `${hio.hex}`, the enlarged
       |  g and s one step hotter in VRO `${vro.hex}` — a heat gradient inside the word. Backgrounds: TIP or
       |  ACG (both oranges fail contrast on the light surfaces, even at logo sizes — see the contrast table).
       |  **Exception (BR 2026-07-20): the Calm light header carries the canonical mark on DLW** — logos are
       |  WCAG-exempt, and the near-white ground is just bright enough for the oranges to read
       |  (VRO ${f"${ratio(vro.hex, dlw.hex)}%.2f"}, HIO ${f"${ratio(hio.hex, dlw.hex)}%.2f"}); on bone-white CTIP they still wash.
       |- **Light-surface variant (CANDIDATE, not yet ratified):** letters in TIP `${tip.hex}`, g and s in
       |  temper blue `${tb.hex}` — shown on the preview's light panel for judgment.
       |- **Small variant:** the enlarged `gs` pair extracted alone (favicon, statusline brand) — same
       |  colors, on an ACG rounded tile; sized specimens at 64/32/16 px in the logo lab.
       |
       |TODO for the SM155 logo family: settle the VRO push, outline the text to SVG paths (so the mark
       |stops depending on Fira being installed), export the color/black-white/big/small variants, and
       |ratify or replace the light-surface colors.
       |
       |## Further reading
       |
       |* Forging (en) == Smide (sv): [en](https://en.wikipedia.org/wiki/Forging) · [sv](https://sv.wikipedia.org/wiki/Smide)
       |* Tempering (en) == Anlöpning (sv): [en](https://en.wikipedia.org/wiki/Tempering_%28metallurgy%29) · [sv](https://sv.wikipedia.org/wiki/Anl%C3%B6pning)
       |* Annealing (en) == Glödgning (sv): [en](https://en.wikipedia.org/wiki/Annealing_%28materials_science%29) · [sv](https://sv.wikipedia.org/wiki/Gl%C3%B6dgning)
       |* Anvil (en) == Städ (sv): [en](https://en.wikipedia.org/wiki/Anvil) · [sv](https://sv.wikipedia.org/wiki/St%C3%A4d)
       |""".stripMargin.replace("@CONTRAST-TABLE@", contrastTable)
       // NB the table is substituted AFTER stripMargin: its rows start with `|`, which stripMargin
       // would otherwise eat as margin chars (live bug on first generation, 2026-07-20).

  // ---------- shared html bits ----------
  def cssVars: String = (palette ++ surfaceTokens).map(c => s"    --${c.css}: ${c.hex};").mkString("\n")

  def wordmark(gsHex: Hex = ""): String =
    val style = if gsHex.isEmpty then "" else s""" style="color:$gsHex""""
    s"""<span class="gs"$style>g</span>en<span class="gs"$style>s</span>calator"""

  // ---------- preview-GENERATED.html ----------
  def preview: String =
    s"""<!DOCTYPE html>
       |<html lang="en">
       |<head>
       |<meta charset="utf-8">
       |<meta name="viewport" content="width=device-width, initial-scale=1">
       |<title>genscalator design language — preview</title>
       |$generatedNote
       |<style>
       |  :root {
       |$cssVars
       |    --sans: "Fira Sans", system-ui, sans-serif;
       |    --mono: "Fira Code", ui-monospace, monospace;
       |  }
       |  * { box-sizing: border-box; margin: 0; }
       |  body { font-family: var(--sans); background: #888; padding: 1rem; }
       |  .page { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; max-width: 1200px; margin: 0 auto; }
       |  @media (max-width: 800px) { .page { grid-template-columns: 1fr; } }
       |  .panel { padding: 2rem; border-radius: 8px; }
       |
       |  .dark { background: var(--${tip.css}); color: var(--${ctip.css}); }
       |  .dark .surface { background: var(--${acg.css}); }
       |  .dark h1, .dark h2 { color: var(--${hio.css}); }
       |  .dark h1 { border-bottom: 4px solid var(--${tb.css}); } /* the quiet temper-blue seam the theme defines (--rule); was missing from the preview, BR spot 2026-07-20 */
       |  .dark .accent { color: var(--${vro.css}); }
       |  .dark a { color: var(--${cvro.css}); }
       |  .dark a:visited { color: var(--${chio.css}); }
       |  .dark .muted { color: var(--${cacg.css}); }
       |  .dark code, .dark pre { background: var(--${acg.css}); color: var(--${ctip.css}); }
       |  .dark .kw { color: var(--${hio.css}); }
       |  .dark .str { color: var(--${chio.css}); }
       |
       |  .light { background: var(--${ctip.css}); color: var(--${tip.css}); }
       |  .light .surface { background: var(--${cacg.css}); }
       |  .light h1, .light h2 { color: var(--${tip.css}); }
       |  .light h1 { border-bottom: 4px solid var(--${hio.css}); }
       |  .light .accent { color: var(--${acg.css}); }
       |  .light a { color: var(--${tb.css}); }
       |  .light a:visited { color: var(--${tip.css}); }
       |  .light .muted { color: var(--${acg.css}); }
       |  .light code, .light pre { background: var(--${tip.css}); color: var(--${ctip.css}); }
       |  .light .kw { color: var(--${hio.css}); }
       |  .light .str { color: var(--${cvro.css}); }
       |
       |  .calm-dark { background: var(--${dng.css}); color: var(--${dlw.css}); }
       |  .calm-dark .surface { background: var(--${tip.css}); }
       |  .calm-dark h1, .calm-dark h2 { color: var(--${dlw.css}); }
       |  .calm-dark h1 { border-bottom: 4px solid var(--${ash.css}); }
       |  .calm-dark a { color: var(--${chio.css}); }
       |  .calm-dark .muted { color: var(--${cacg.css}); }
       |  .calm-dark code, .calm-dark pre { background: var(--${tip.css}); color: var(--${ctip.css}); }
       |  .calm-dark .kw { color: var(--${hio.css}); }
       |  .calm-dark .str { color: var(--${chio.css}); }
       |  .calm-dark .logo { color: var(--${cacg.css}); }
       |  .calm-dark .logo .gs { color: var(--${chio.css}); }
       |
       |  .calm-light { background: var(--${dlw.css}); color: var(--${dng.css}); }
       |  .calm-light .surface { background: var(--${cacg.css}); }
       |  .calm-light h1, .calm-light h2 { color: var(--${dng.css}); }
       |  .calm-light h1 { border-bottom: 4px solid var(--${ash.css}); }
       |  .calm-light a { color: var(--${tb.css}); }
       |  .calm-light .muted { color: var(--${ash.css}); }
       |  .calm-light code, .calm-light pre { background: var(--${tip.css}); color: var(--${ctip.css}); }
       |  .calm-light .kw { color: var(--${hio.css}); }
       |  .calm-light .str { color: var(--${cvro.css}); }
       |  .calm-light .logo { color: var(--${hio.css}); }
       |  .calm-light .logo .gs { color: var(--${vro.css}); }
       |
       |  h1 { font-size: 1.6rem; margin-bottom: .25rem; padding-bottom: .25rem; }
       |  h2 { font-size: 1.1rem; margin: 1.2rem 0 .4rem; }
       |  p { line-height: 1.55; margin-bottom: .6rem; }
       |  pre { font-family: var(--mono); font-size: .85rem; padding: .8rem 1rem; border-radius: 6px; overflow-x: auto; margin: .5rem 0 1rem; }
       |  code { font-family: var(--mono); padding: .05rem .3rem; border-radius: 4px; }
       |  .surface { padding: 1rem; border-radius: 6px; margin: .8rem 0; }
       |  .chips { display: flex; gap: .5rem; flex-wrap: wrap; margin: .6rem 0 1rem; }
       |  .chip { font-family: var(--mono); font-size: .8rem; font-weight: bold; padding: .15rem .55rem; border-radius: 3px; }
       |  .chip.spend  { background: var(--${hio.css});  color: var(--${tip.css}); }
       |  .chip.smart  { background: var(--${vbg.css});  color: var(--${tip.css}); }
       |  .chip.cold   { background: var(--${chio.css}); color: var(--${tip.css}); }
       |  .chip.vigil  { background: var(--${vro.css});  color: var(--${tip.css}); } /* TIP text: bone drops to ~3.0 on the redder VRO */
       |  .chip.pink   { background: var(--${npp.css});  color: #ffffff; }
       |  .logo { font-family: var(--mono); font-weight: $logoWeight; font-size: 2.2rem; margin-bottom: 1rem; }
       |  .logo .gs { font-size: ${logoGsScale}em; }
       |  .dark .logo { color: var(--${hio.css}); }
       |  .dark .logo .gs { color: var(--${vro.css}); }
       |  .light .logo { color: var(--${tip.css}); }
       |  .light .logo .gs { color: var(--${tb.css}); }
       |  .swatches { display: grid; grid-template-columns: repeat(3, 1fr); gap: .5rem; margin-top: 1rem; }
       |  .sw { border-radius: 5px; padding: .5rem; font-family: var(--mono); font-size: .68rem; min-height: 3.2rem; }
       |</style>
       |</head>
       |<body>
       |<div class="page">
       |
       |  <section class="panel dark">
       |    <div class="logo">${wordmark()}</div>
       |    <h1>Forgy dark</h1>
       |    <p class="muted">tempered-iron purple ground · bone-white body · glow-orange headings</p>
       |    <div class="chips">
       |      <span class="chip spend">TokSpend</span><span class="chip smart">SmartZone</span>
       |      <span class="chip cold">ColdStart</span><span class="chip vigil">RotVigil</span><span class="chip pink">Racing</span>
       |    </div>
       |    <h2>Body and links</h2>
       |    <p>The exit banks the fire; the fresh agent blows the <span class="accent">warp ember</span>
       |       back into flame. Read the <a href="README.md">design language</a> — palette, contrast
       |       table and logo spec are all generated from one Scala source.</p>
       |    <div class="surface">
       |      <p>A raised surface in anvil-coal graphite. Inline code like <code>tt forge</code> sits on it.</p>
       |    </div>
       |    <h2>Code</h2>
       |    <pre><span class="kw">object</span> Forge:
       |  <span class="kw">val</span> ember = bank(fire)     <span class="str">// survives the warp</span>
       |  <span class="kw">def</span> morning = blow(ember)  <span class="str">// back into flame</span></pre>
       |    <div class="swatches">
       |      <div class="sw" style="background:${hio.hex};color:${tip.hex}">HIO ${hio.hex}</div>
       |      <div class="sw" style="background:${vro.hex};color:${ctip.hex}">VRO ${vro.hex}</div>
       |      <div class="sw" style="background:${cvro.hex};color:${tip.hex}">CVRO ${cvro.hex}</div>
       |      <div class="sw" style="background:${chio.hex};color:${tip.hex}">CHIO ${chio.hex}</div>
       |      <div class="sw" style="background:${vbg.hex};color:${tip.hex}">VBG ${vbg.hex}</div>
       |      <div class="sw" style="background:${npp.hex};color:#ffffff">NPP ${npp.hex}</div>
       |    </div>
       |  </section>
       |
       |  <section class="panel light">
       |    <div class="logo">${wordmark()}</div>
       |    <h1>Smither light</h1>
       |    <p class="muted">bone-white ground · tempered-purple body · hot-iron rule · temper-blue links</p>
       |    <div class="chips">
       |      <span class="chip spend">TokSpend</span><span class="chip smart">SmartZone</span>
       |      <span class="chip cold">ColdStart</span><span class="chip vigil">RotVigil</span><span class="chip pink">Racing</span>
       |    </div>
       |    <h2>Body and links</h2>
       |    <p>The exit banks the fire; the fresh agent blows the <span class="accent">warp ember</span>
       |       back into flame. Read the <a href="README.md">design language</a> — palette, contrast
       |       table and logo spec are all generated from one Scala source.</p>
       |    <div class="surface">
       |      <p>A raised surface in cold gray. Inline code like <code>tt forge</code> inverts to the dark pair.</p>
       |    </div>
       |    <h2>Code</h2>
       |    <pre><span class="kw">object</span> Forge:
       |  <span class="kw">val</span> ember = bank(fire)     <span class="str">// survives the warp</span>
       |  <span class="kw">def</span> morning = blow(ember)  <span class="str">// back into flame</span></pre>
       |    <div class="swatches">
       |      <div class="sw" style="background:${tb.hex};color:${ctip.hex}">TB ${tb.hex}</div>
       |      <div class="sw" style="background:${ctip.hex};color:${tip.hex}">CTIP ${ctip.hex}</div>
       |      <div class="sw" style="background:${cacg.hex};color:${acg.hex}">CACG ${cacg.hex}</div>
       |      <div class="sw" style="background:${hio.hex};color:${tip.hex}">HIO ${hio.hex}</div>
       |      <div class="sw" style="background:${tip.hex};color:${ctip.hex}">TIP ${tip.hex}</div>
       |      <div class="sw" style="background:${acg.hex};color:${cacg.hex}">ACG ${acg.hex}</div>
       |    </div>
       |  </section>
       |
       |  <section class="panel calm-dark">
       |    <div class="logo">${wordmark()}</div>
       |    <h1>Calm dark</h1>
       |    <p class="muted">dark-night-graphite ground · day-light-white text · one quiet accent</p>
       |    <div class="chips">
       |      <span class="chip spend">TokSpend</span><span class="chip smart">SmartZone</span>
       |      <span class="chip cold">ColdStart</span><span class="chip vigil">RotVigil</span><span class="chip pink">Racing</span>
       |    </div>
       |    <h2>Body and links</h2>
       |    <p>Headings keep the text color and the seam turns coal-ash; only <a href="README.md">links</a>
       |       carry an accent. The chips and the logo still land, muted to the calm register.</p>
       |    <div class="surface">
       |      <p>A raised surface in tempered purple. Inline code like <code>tt forge</code> keeps the TIP ground.</p>
       |    </div>
       |    <h2>Code</h2>
       |    <pre><span class="kw">object</span> Forge:
       |  <span class="kw">val</span> ember = bank(fire)     <span class="str">// survives the warp</span>
       |  <span class="kw">def</span> morning = blow(ember)  <span class="str">// back into flame</span></pre>
       |  </section>
       |
       |  <section class="panel calm-light">
       |    <div class="logo">${wordmark()}</div>
       |    <h1>Calm light</h1>
       |    <p class="muted">day-light-white ground · dark-night-graphite text · temper-blue links</p>
       |    <div class="chips">
       |      <span class="chip spend">TokSpend</span><span class="chip smart">SmartZone</span>
       |      <span class="chip cold">ColdStart</span><span class="chip vigil">RotVigil</span><span class="chip pink">Racing</span>
       |    </div>
       |    <h2>Body and links</h2>
       |    <p>Headings keep the text color and the seam turns coal-ash; only <a href="README.md">links</a>
       |       carry an accent. The chips and the logo still land, muted to the calm register.</p>
       |    <div class="surface">
       |      <p>A raised surface in cold gray. Inline code like <code>tt forge</code> keeps the TIP ground.</p>
       |    </div>
       |    <h2>Code</h2>
       |    <pre><span class="kw">object</span> Forge:
       |  <span class="kw">val</span> ember = bank(fire)     <span class="str">// survives the warp</span>
       |  <span class="kw">def</span> morning = blow(ember)  <span class="str">// back into flame</span></pre>
       |  </section>
       |
       |</div>
       |</body>
       |</html>
       |""".stripMargin

  // ---------- design.css + design.js: the SHARED tokens/components every genscalator page links ----------
  // SM155 slice 1 + the four-theme dropdown (BR 2026-07-20): palette custom properties, FOUR theme
  // variable-sets keyed off data-theme on <html> (Smither light default, Forgy dark as the OS-dark
  // default, Calm light/dark on the DLW/DNG surface tokens), and the shared components (logo, chips,
  // the theme dropdown). Pages keep their own layout CSS and consume these variables. design.js and
  // the blog template both embed themeScript, which fills <select id="theme-select"> from the SAME
  // themes list that names the CSS variable-sets — labels and selectors cannot drift apart.

  val themes: Vector[(String, String)] = Vector(
    "forgy-dark"    -> "Forgy dark",
    "smither-light" -> "Smither light",
    "calm-dark"     -> "Calm dark",
    "calm-light"    -> "Calm light",
  )

  private def varSet(pairs: (String, Color)*): String =
    pairs.map((k, c) => s"  --$k: var(--${c.css});").mkString("\n")

  // Semantic variable-sets for design.css. Calm = same fonts, logo and chips, but text and headings
  // drop the brand colors (fg doubles as head), links keep ONE accent, and code stays TIP-grounded
  // in all four themes so the single syntax-token color-set keeps its measured contrast everywhere.
  def smitherVars = varSet("bg" -> ctip, "fg" -> tip, "head" -> tip, "link" -> tb, "visited" -> tip,
    "muted" -> ash, "link-hover" -> tip, "bg-soft" -> cacg, "quote-border" -> cacg,
    "code-bg" -> tip, "code-fg" -> ctip, "border" -> acg, "th-bg" -> cacg, "logo-fg" -> tip, "logo-gs" -> tb, "rule" -> hio)
  def forgyVars = varSet("bg" -> tip, "fg" -> ctip, "head" -> hio, "link" -> cvro, "visited" -> chio,
    "muted" -> cacg, "link-hover" -> chio, "bg-soft" -> acg, "quote-border" -> ash,
    "code-bg" -> acg, "code-fg" -> ctip, "border" -> cacg, "th-bg" -> acg, "logo-fg" -> hio, "logo-gs" -> vro, "rule" -> tb)
  def calmDarkVars = varSet("bg" -> dng, "fg" -> dlw, "head" -> dlw, "link" -> chio, "visited" -> chio,
    "muted" -> cacg, "link-hover" -> cvro, "bg-soft" -> tip, "quote-border" -> ash,
    "code-bg" -> tip, "code-fg" -> ctip, "border" -> ash, "th-bg" -> tip, "logo-fg" -> cacg, "logo-gs" -> chio, "rule" -> ash)
  // Calm light carries the CANONICAL orange wordmark (BR 2026-07-20): logos are WCAG-exempt, and
  // the DLW ground is bright enough that the oranges read (VRO ~4.5, HIO ~3.3 — vs washing on CTIP).
  def calmLightVars = varSet("bg" -> dlw, "fg" -> dng, "head" -> dng, "link" -> tb, "visited" -> tb,
    "muted" -> ash, "link-hover" -> tip, "bg-soft" -> cacg, "quote-border" -> cacg,
    "code-bg" -> tip, "code-fg" -> ctip, "border" -> cacg, "th-bg" -> cacg, "logo-fg" -> hio, "logo-gs" -> vro, "rule" -> ash)

  // The dropdown script, shared VERBATIM by design.js and the blog template: applies the saved
  // theme before first paint, then fills <select id="theme-select"> on DOM ready. Automatic (the
  // default) leaves data-theme unset, so the CSS default pair (the CALM pair, BR 2026-07-20, via
  // prefers-color-scheme) stays live and keeps following OS changes.
  def themeScript: String =
    val opts = (("auto" -> "Automatic") +: themes).map((v, l) => s"""{v:"$v",l:"$l"}""").mkString("[", ",", "]")
    s"""(function () {
       |  var KEY = "gs-theme";
       |  var THEMES = $opts;
       |  var root = document.documentElement;
       |  function get() {
       |    try {
       |      var v = localStorage.getItem(KEY);
       |      if (!v) { /* migrate the two legacy two-state keys */
       |        var old = localStorage.getItem("br-theme") || localStorage.getItem("gs-design-theme");
       |        if (old === "dark") v = "forgy-dark";
       |        if (old === "light") v = "smither-light";
       |      }
       |      return THEMES.some(function (t) { return t.v === v; }) ? v : null;
       |    } catch (e) { return null; }
       |  }
       |  function apply(v) {
       |    if (v && v !== "auto") root.setAttribute("data-theme", v);
       |    else root.removeAttribute("data-theme"); /* Automatic: the Calm pair follows the OS */
       |  }
       |  apply(get()); /* before first paint */
       |  document.addEventListener("DOMContentLoaded", function () {
       |    var sel = document.getElementById("theme-select");
       |    if (!sel) return;
       |    THEMES.forEach(function (t) {
       |      var o = document.createElement("option");
       |      o.value = t.v;
       |      o.textContent = t.l;
       |      sel.appendChild(o);
       |    });
       |    sel.value = get() || "auto";
       |    sel.addEventListener("change", function () {
       |      try { localStorage.setItem(KEY, sel.value); } catch (e) { /* still apply for this page */ }
       |      apply(sel.value);
       |    });
       |  });
       |})();""".stripMargin

  // Self-hosted Fira faces, root-absolute so ANY /genscalator/** page resolves them (the deployed
  // /genscalator/fonts/ dir is live-verified, meta-minion push-10). ONE def serves design.css and
  // the blog template, so the font story cannot fork.
  def fontFacesCss: String =
    s"""@font-face { font-family: "Fira Code"; src: url("/genscalator/fonts/FiraCode-Regular.woff2") format("woff2");
       |  font-weight: 400; font-style: normal; font-display: swap; }
       |@font-face { font-family: "Fira Sans"; src: url("/genscalator/fonts/FiraSans-Regular.woff2") format("woff2");
       |  font-weight: 400; font-style: normal; font-display: swap; }
       |@font-face { font-family: "Fira Sans"; src: url("/genscalator/fonts/FiraSans-Medium.woff2") format("woff2");
       |  font-weight: 500; font-style: normal; font-display: swap; }
       |@font-face { font-family: "Fira Sans"; src: url("/genscalator/fonts/FiraSans-SemiBold.woff2") format("woff2");
       |  font-weight: 600; font-style: normal; font-display: swap; }""".stripMargin

  // The shared PROSE component: the blog's reading typography, scoped under .prose so any page
  // (a security doc, a design-language page, a future doc) reads exactly like a blog post.
  // Typography only — the page owns column width, margins and padding.
  def proseCss: String =
    s"""/* prose: the house reading column (blog-identical typography; page owns the layout box) */
       |.prose { font-family: var(--sans); font-size: clamp(1rem, 0.95rem + 0.3vw, 1.125rem); line-height: 1.65; color: var(--fg); }
       |.prose h1, .prose h2, .prose h3, .prose h4 { line-height: 1.25; margin: 2em 0 0.6em; font-weight: 700; color: var(--fg); }
       |.prose h1 { font-size: 1.85em; margin-top: 0.4em; border-bottom: 4px solid var(--rule); padding-bottom: 0.2em; }
       |.prose h2 { font-size: 1.4em; }
       |.prose h3 { font-size: 1.15em; }
       |.prose h4 { font-size: 1em; color: var(--muted); }
       |.prose p { margin: 0 0 1.1em; }
       |.prose p, .prose li { overflow-wrap: break-word; }
       |.prose a { color: var(--link); text-decoration: underline; text-decoration-thickness: 1px; text-underline-offset: 0.15em; }
       |.prose a:hover { color: var(--link-hover); }
       |.prose strong { font-weight: 700; }
       |.prose em { font-style: italic; }
       |.prose ul, .prose ol { margin: 0 0 1.1em; padding-left: 1.5em; }
       |.prose li { margin-bottom: 0.3em; }
       |.prose blockquote { margin: 1.2em 0; padding: 0.2em 1.1em; border-left: 3px solid var(--quote-border); color: var(--muted); }
       |.prose code, .prose pre { font-family: var(--mono); }
       |.prose code { background: var(--code-bg); color: var(--code-fg); border-radius: 4px; padding: 0.12em 0.35em; font-size: 0.88em; overflow-wrap: break-word; }
       |.prose pre { background: var(--code-bg); border: 1px solid var(--border); border-radius: 6px; padding: 0.9rem 1.1rem; margin: 1.2em 0; overflow-x: auto; line-height: 1.5; }
       |.prose pre > code { background: none; border-radius: 0; padding: 0; font-size: 0.85em; overflow-wrap: normal; }
       |.prose img { max-width: 100%; height: auto; }
       |.prose table { display: block; width: max-content; max-width: 100%; overflow-x: auto; border-collapse: collapse; margin: 1.2em 0; font-size: 0.95em; }
       |.prose th, .prose td { border: 1px solid var(--border); padding: 0.45em 0.8em; text-align: left; vertical-align: top; }
       |.prose thead th { background: var(--bg-soft); font-weight: 600; }
       |.prose hr { border: none; border-top: 1px solid var(--border); margin: 2.5em 0; }
       |.tok-kw { color: var(--tok-kw); font-weight: 700; }
       |.tok-soft { color: var(--tok-soft); }
       |.tok-str { color: var(--tok-str); }
       |.tok-num { color: var(--tok-num); }
       |.tok-comment { color: var(--tok-comment); font-style: italic; }
       |.tok-type { color: var(--tok-type); }
       |.tok-def { color: var(--tok-def); }""".stripMargin

  def designCss: String =
    s"""/* GENERATED by DesignLang.scala - DO NOT EDIT. Edit DesignLang.scala and re-run:
       |   scala-cli run media/design-language/DesignLang.scala --main-class generateDesignLanguage
       |   The genscalator design language: palette tokens + theme variable-sets + shared components.
       |   Themes (data-theme on <html>, dropdown filled by design.js): Automatic (default, the Calm
       |   pair follows the OS scheme) / Smither light / Forgy dark / Calm dark / Calm light. */
       |$fontFacesCss
       |/* Automatic (default, no data-theme): Calm light — semantic vars flip per theme, palette vars never change */
       |:root {
       |$cssVars
       |  --mono: "Fira Code", "Fira Mono", ui-monospace, monospace;
       |  --sans: "Fira Sans", system-ui, sans-serif;
       |  --tok-kw: var(--${hio.css});
       |  --tok-soft: var(--${cacg.css});
       |  --tok-str: var(--${vbg.css});
       |  --tok-num: var(--${chio.css});
       |  --tok-comment: var(--${ash.css});
       |  --tok-type: var(--${cvro.css});
       |  --tok-def: var(--${vro.css});
       |$calmLightVars
       |  color-scheme: light;
       |}
       |/* Automatic + OS dark: Calm dark */
       |@media (prefers-color-scheme: dark) {
       |:root:not([data-theme]) {
       |$calmDarkVars
       |  color-scheme: dark;
       |}
       |}
       |/* Smither light */
       |:root[data-theme="smither-light"] {
       |$smitherVars
       |  color-scheme: light;
       |}
       |/* Forgy dark — the rule: heading and its line must differ, HIO heading over a quiet temper-blue seam */
       |:root[data-theme="forgy-dark"] {
       |$forgyVars
       |  color-scheme: dark;
       |}
       |/* Calm dark: day-light-white text on dark-night-graphite, brand colors leave the text */
       |:root[data-theme="calm-dark"] {
       |$calmDarkVars
       |  color-scheme: dark;
       |}
       |/* Calm light: dark-night-graphite text on day-light-white */
       |:root[data-theme="calm-light"] {
       |$calmLightVars
       |  color-scheme: light;
       |}
       |/* the wordmark (frozen: Fira Code $logoWeight, gs ${logoGsScale}em) */
       |.logo { font-family: var(--mono); font-weight: $logoWeight; color: var(--logo-fg); }
       |.logo .gs { font-size: ${logoGsScale}em; color: var(--logo-gs); }
       |/* mode chips */
       |.chip { font-family: var(--mono); font-size: .8rem; font-weight: bold; padding: .15rem .55rem; border-radius: 3px; }
       |.chip.spend  { background: var(--${hio.css});  color: var(--${tip.css}); }
       |.chip.smart  { background: var(--${vbg.css});  color: var(--${tip.css}); }
       |.chip.cold   { background: var(--${chio.css}); color: var(--${tip.css}); }
       |.chip.vigil  { background: var(--${vro.css});  color: var(--${tip.css}); }
       |.chip.pink   { background: var(--${npp.css});  color: #ffffff; }
       |/* the theme dropdown (filled and wired by design.js); z-index clears hero scrims/overlays (landing z 1-2) */
       |#theme-select { position: fixed; top: 1rem; right: 1rem; z-index: 10; font-family: var(--mono);
       |  font-size: .8rem; font-weight: bold; padding: .3rem .7rem; border-radius: 4px;
       |  border: 1px solid var(--border); background: var(--code-bg); color: var(--code-fg); cursor: pointer; }
       |$proseCss
       |""".stripMargin

  def designJs: String =
    s"""/* GENERATED by DesignLang.scala - DO NOT EDIT. The theme dropdown: applies the saved
       |   theme before first paint, fills <select id="theme-select"> (styled by design.css),
       |   persists in localStorage; Automatic (default) = the Calm pair following the OS scheme. */
       |$themeScript
       |""".stripMargin

  // ---------- index.html: the README rendered via the house ssg (Smither-light theme) ----------
  def indexTemplate: String =
    s"""<!DOCTYPE html>
       |<html lang="en">
       |<head>
       |<meta charset="utf-8">
       |<meta name="viewport" content="width=device-width, initial-scale=1">
       |<title>{{TITLE}}</title>
       |$generatedNote
       |<link rel="stylesheet" href="design.css">
       |<style>
       |  * { box-sizing: border-box; }
       |  body { font-family: var(--sans); background: var(--bg); color: var(--fg);
       |         max-width: 60rem; margin: 0 auto; padding: 2rem 1.5rem 4rem; line-height: 1.55; }
       |  h1, h2, h3, h4 { color: var(--head); margin: 1.4em 0 .4em; }
       |  h1 { border-bottom: 4px solid var(--rule); padding-bottom: .25rem; }
       |  a { color: var(--link); }
       |  a:visited { color: var(--visited); }
       |  pre, code { font-family: var(--mono); }
       |  pre { background: var(--code-bg); color: var(--code-fg); padding: .8rem 1rem;
       |        border-radius: 6px; overflow-x: auto; }
       |  code { background: var(--code-bg); color: var(--code-fg); padding: .05rem .3rem; border-radius: 4px; }
       |  pre code { padding: 0; }
       |  table { border-collapse: collapse; margin: 1rem 0; }
       |  th, td { border: 1px solid var(--border); padding: .3rem .6rem; font-size: .9rem; }
       |  th { background: var(--th-bg); }
       |  .logo { font-size: 2.2rem; margin-bottom: .2rem; }
       |  nav { font-family: var(--mono); font-size: .85rem; margin-bottom: 2rem; }
       |</style>
       |</head>
       |<body>
       |<select id="theme-select" aria-label="Theme"></select>
       |<script src="design.js"></script>
       |<div class="logo">${wordmark()}</div>
       |<nav><a href="preview-GENERATED.html">preview</a> · <a href="logo-lab-GENERATED.html">logo lab</a> ·
       |  <a href="mascot-lab-GENERATED.html">mascot lab</a> · <a href="DesignLang.scala">source of truth</a></nav>
       |{{CONTENT}}
       |</body>
       |</html>
       |""".stripMargin

  def index: String = Ssg.renderPage(readme, indexTemplate)

  // ---------- logo-lab-GENERATED.html ----------
  def logoLab: String =
    def markRow(cls: String) = s"""    <div class="mark big $cls">${wordmark()}</div>"""
    val gridRows = (for w <- Vector(500, 700); s <- Vector(120, 135, 150) yield (w, s))
    def rows(ws: Vector[(Int, Int)]) = ws.map((w, s) => markRow(s"w$w s$s")).mkString("\n")
    val candidateRows = vroCandidates.map(hex => s"""    <div class="mark big w$logoWeight s135">${wordmark(hex)}</div>""").mkString("\n")
    val candidateRowsLight = candidateRows
    def wordmarkLight = s"""<span class="gs" style="color:${tb.hex}">g</span>en<span class="gs" style="color:${tb.hex}">s</span>calator"""
    val lightVariantSection =
      s"""  <section class="panel light">
         |    <div class="label">Smither-light VARIANT (TIP letters, temper-blue gs) — the light-surface mark candidate: big / heading / inline + gs tile</div>
         |    <div class="mark big w$logoWeight s135" style="color:${tip.hex}">$wordmarkLight</div>
         |    <div class="mark mid w$logoWeight s135" style="color:${tip.hex}">$wordmarkLight</div>
         |    <div class="mark tiny w$logoWeight s135" style="color:${tip.hex}">$wordmarkLight</div>
         |    <div class="favrow">
         |      <div class="fav f64" style="background:${cacg.hex}"><span class="mark w$logoWeight" style="color:${tip.hex}"><span class="gs" style="color:${tb.hex}">g</span><span class="gs" style="color:${tb.hex}">s</span></span></div>
         |      <div class="fav f32" style="background:${cacg.hex}"><span class="mark w$logoWeight" style="color:${tip.hex}"><span class="gs" style="color:${tb.hex}">g</span><span class="gs" style="color:${tb.hex}">s</span></span></div>
         |    </div>
         |  </section>""".stripMargin
    s"""<!DOCTYPE html>
       |<html lang="en">
       |<head>
       |<meta charset="utf-8">
       |<meta name="viewport" content="width=device-width, initial-scale=1">
       |<title>genscalator logo lab</title>
       |$generatedNote
       |<style>
       |  :root {
       |$cssVars
       |    --mono: "Fira Code", "Fira Mono", ui-monospace, monospace;
       |  }
       |  * { box-sizing: border-box; margin: 0; }
       |  body { font-family: system-ui, sans-serif; background: #888; padding: 1rem; }
       |  .lab { max-width: 1100px; margin: 0 auto; display: grid; gap: 1rem; }
       |  .panel { border-radius: 8px; padding: 1.5rem 2rem; }
       |  .tip { background: var(--${tip.css}); } .acg { background: var(--${acg.css}); } .light { background: var(--${ctip.css}); }
       |  .label { font-size: .75rem; color: #ccc; font-family: var(--mono); margin: 1.1rem 0 .2rem; }
       |  .light .label { color: #555; }
       |  .mark { font-family: var(--mono); color: var(--${hio.css}); }
       |  .mark .gs { color: var(--${vro.css}); }
       |  .w500 { font-weight: 500; } .w700 { font-weight: 700; }
       |  .s120 .gs { font-size: 1.20em; } .s135 .gs { font-size: 1.35em; } .s150 .gs { font-size: 1.50em; }
       |  .big { font-size: 3rem; } .mid { font-size: 1.6rem; } .tiny { font-size: .95rem; }
       |  .favrow { display: flex; gap: 1rem; align-items: center; margin-top: .4rem; }
       |  .fav { background: var(--${acg.css}); border-radius: 20%; display: grid; place-items: center; }
       |  .f64 { width: 64px; height: 64px; font-size: 30px; }
       |  .f32 { width: 32px; height: 32px; font-size: 15px; }
       |  .f16 { width: 16px; height: 16px; font-size: 8px; }
       |</style>
       |</head>
       |<body>
       |<div class="lab">
       |
       |  <section class="panel tip">
       |    <div class="label">weight 500 · gs 1.20 / 1.35 / 1.50 — on tempered-iron purple (frozen pick: w$logoWeight s${(logoGsScale * 100).toInt})</div>
       |${rows(gridRows.take(3))}
       |    <div class="label">weight 700 · gs 1.20 / 1.35 / 1.50</div>
       |${rows(gridRows.drop(3))}
       |  </section>
       |
       |  <section class="panel acg">
       |    <div class="label">same six on anvil-coal graphite</div>
       |${rows(gridRows)}
       |  </section>
       |
       |  <section class="panel tip">
       |    <div class="label">smaller sizes (frozen spec): heading and inline</div>
       |    <div class="mark mid w$logoWeight s135">${wordmark()}</div>
       |    <div class="mark tiny w$logoWeight s135">${wordmark()}</div>
       |    <div class="label">the small variant: gs extracted (favicon / statusline brand)</div>
       |    <div class="favrow">
       |      <div class="fav f64"><span class="mark w$logoWeight"><span class="gs">g</span><span class="gs">s</span></span></div>
       |      <div class="fav f32"><span class="mark w$logoWeight"><span class="gs">g</span><span class="gs">s</span></span></div>
       |      <div class="fav f16"><span class="mark w$logoWeight"><span class="gs">g</span><span class="gs">s</span></span></div>
       |    </div>
       |  </section>
       |
       |  <section class="panel tip">
       |    <div class="label">VRO candidates for the hot gs (frozen weight/scale): current ${vro.hex} then ${vroCandidates.mkString(" · ")}</div>
       |    <div class="mark big w$logoWeight s135">${wordmark()}</div>
       |$candidateRows
       |  </section>
       |
       |  <section class="panel light">
       |    <div class="label">VRO on BONE-WHITE (its light-theme accent ground): current ${vro.hex} then ${vroCandidates.mkString(" · ")}
       |      — judge the gs redness where the light theme actually uses it (smaller HIO letters stay
       |      washed here on purpose: the full color mark remains DARK-surface; light pages use the
       |      TIP+temper-blue variant)</div>
       |    <div class="mark big w$logoWeight s135">${wordmark()}</div>
       |$candidateRowsLight
       |  </section>
       |
       |@LIGHT-VARIANT-SECTION@
       |
       |</div>
       |</body>
       |</html>
       |""".stripMargin.replace("@LIGHT-VARIANT-SECTION@", lightVariantSection)
       // (substituted after stripMargin, same trick as the contrast table)

  // Blog-template variable-sets (raw hex: blog pages are self-contained). Same theme mapping as the
  // design.css sets above, in the blog's own var names; the tok- vars live once in :root and are
  // never overridden because code keeps the TIP ground in every theme. Automatic default = Calm.
  private def blogVarSet(pairs: (String, Color)*): String =
    pairs.map((k, c) => s"  --$k: ${c.hex};").mkString("\n")
  // brand-hover: the wordmark's hover color must CONTRAST its resting color — Smither light hovers
  // to hot iron (TIP -> TB was two near-identical dark blues, BR 2026-07-20); the others keep their
  // accent, which already jumps (orange -> blue, gray -> blue).
  def blogSmitherVars = blogVarSet("bg" -> ctip, "bg-soft" -> cacg, "text" -> tip, "text-muted" -> ash,
    "accent" -> tb, "accent-hover" -> tip, "border" -> cacg, "code-bg" -> tip, "code-text" -> ctip,
    "quote-border" -> cacg, "rule" -> hio, "brand-fg" -> tip, "brand-gs" -> tb, "brand-hover" -> hio)
  def blogForgyVars = blogVarSet("bg" -> tip, "bg-soft" -> acg, "text" -> ctip, "text-muted" -> cacg,
    "accent" -> cvro, "accent-hover" -> chio, "border" -> ash, "code-bg" -> acg, "code-text" -> ctip,
    "quote-border" -> ash, "rule" -> tb, "brand-fg" -> hio, "brand-gs" -> vro, "brand-hover" -> cvro)
  def blogCalmDarkVars = blogVarSet("bg" -> dng, "bg-soft" -> tip, "text" -> dlw, "text-muted" -> cacg,
    "accent" -> chio, "accent-hover" -> cvro, "border" -> ash, "code-bg" -> tip, "code-text" -> ctip,
    "quote-border" -> ash, "rule" -> ash, "brand-fg" -> cacg, "brand-gs" -> chio, "brand-hover" -> chio)
  def blogCalmLightVars = blogVarSet("bg" -> dlw, "bg-soft" -> cacg, "text" -> dng, "text-muted" -> ash,
    "accent" -> tb, "accent-hover" -> tip, "border" -> cacg, "code-bg" -> tip, "code-text" -> ctip,
    "quote-border" -> cacg, "rule" -> ash, "brand-fg" -> hio, "brand-gs" -> vro, "brand-hover" -> tb)

  // ---------- media/blog/_template.html: the ssg blog template, reskinned to the design language ----------
  // GENERATED into media/blog/ (ssg's fixed template name) so the blog palette can never drift from here.
  // The MECHANISMS (TOC sidebar, to-top, footnotes, token classes) are ported verbatim from the
  // 2026-07 hand template; colors, fonts, brand and the h1 rule changed, and the original
  // three-state toggle became the shared four-theme dropdown (themeScript, 2026-07-20).
  // Code blocks are TIP/ACG-grounded in BOTH themes, so ONE token color-set serves both (all
  // tokens measured >= 3.4 on TIP; comments in ASH read muted by design).

  def blogTemplate: String =
    s"""<!doctype html>
       |<html lang="en">
       |<head>
       |<meta charset="utf-8">
       |<meta name="viewport" content="width=device-width, initial-scale=1">
       |<title>{{TITLE}}</title>
       |$generatedNote
       |<style>
       |$fontFacesCss
       |/* Automatic (default, no data-theme): the Calm pair follows the OS scheme.
       |   Palette: media/design-language (GENERATED, do not edit here). The tok- vars live here
       |   ONCE and are never overridden: code keeps the TIP ground in every theme, so the one
       |   measured token color-set serves them all. */
       |:root {
       |$blogCalmLightVars
       |  --tok-kw: ${hio.hex};
       |  --tok-soft: ${cacg.hex};
       |  --tok-str: ${vbg.hex};
       |  --tok-num: ${chio.hex};
       |  --tok-comment: ${ash.hex};
       |  --tok-type: ${cvro.hex};
       |  --tok-def: ${vro.hex};
       |  --mono: "Fira Code", ui-monospace, monospace;
       |  --sans: "Fira Sans", system-ui, sans-serif;
       |  color-scheme: light;
       |}
       |@media (prefers-color-scheme: dark) {
       |:root:not([data-theme]) {
       |$blogCalmDarkVars
       |  color-scheme: dark;
       |}
       |}
       |/* Smither light */
       |:root[data-theme="smither-light"] {
       |$blogSmitherVars
       |  color-scheme: light;
       |}
       |/* Forgy dark */
       |:root[data-theme="forgy-dark"] {
       |$blogForgyVars
       |  color-scheme: dark;
       |}
       |/* Calm dark */
       |:root[data-theme="calm-dark"] {
       |$blogCalmDarkVars
       |  color-scheme: dark;
       |}
       |/* Calm light */
       |:root[data-theme="calm-light"] {
       |$blogCalmLightVars
       |  color-scheme: light;
       |}
       |
       |* { box-sizing: border-box; }
       |
       |html {
       |  -webkit-text-size-adjust: 100%;
       |  scroll-behavior: smooth;
       |}
       |
       |body {
       |  margin: 0;
       |  background: var(--bg);
       |  color: var(--text);
       |  font-family: var(--sans);
       |  font-size: clamp(1rem, 0.95rem + 0.3vw, 1.125rem);
       |  line-height: 1.65;
       |  min-height: 100vh;
       |  display: flex;
       |  flex-direction: column;
       |}
       |
       |.wrap {
       |  width: 100%;
       |  max-width: 70ch;
       |  margin-inline: auto;
       |  padding-inline: clamp(1rem, 4vw, 2rem);
       |}
       |
       |.site-header {
       |  border-bottom: 1px solid var(--border);
       |}
       |.site-header .wrap {
       |  display: flex;
       |  align-items: center;
       |  gap: 1rem;
       |  padding-block: 0.7rem;
       |}
       |.brand {
       |  font-family: var(--mono);
       |  font-weight: $logoWeight;
       |  font-size: 1.05rem;
       |  letter-spacing: 0.02em;
       |  color: var(--brand-fg);
       |  text-decoration: none;
       |}
       |.brand .gs { font-size: ${logoGsScale}em; color: var(--brand-gs); }
       |.brand:hover { color: var(--brand-hover); }
       |.site-nav {
       |  margin-left: auto;
       |  display: flex;
       |  align-items: center;
       |  gap: 1rem;
       |}
       |.site-nav a {
       |  color: var(--text);
       |  text-decoration: none;
       |  font-size: 0.95rem;
       |}
       |.site-nav a:hover {
       |  color: var(--accent);
       |  text-decoration: underline;
       |}
       |
       |.theme-select {
       |  border: 1px solid var(--border);
       |  border-radius: 999px;
       |  background: var(--bg-soft);
       |  color: var(--text);
       |  font: inherit;
       |  font-size: 0.72rem;
       |  line-height: 1;
       |  padding: 0.3rem 0.6rem;
       |  cursor: pointer;
       |}
       |.theme-select:hover { color: var(--accent); }
       |
       |main {
       |  flex: 1;
       |  padding-block: clamp(1.5rem, 5vw, 3rem);
       |}
       |
       |.layout {
       |  width: 100%;
       |  max-width: 64rem;
       |  margin-inline: auto;
       |  padding-inline: clamp(1rem, 4vw, 2rem);
       |  display: flex;
       |  justify-content: center;
       |  align-items: flex-start;
       |  gap: 2.5rem;
       |}
       |.prose {
       |  flex: 1 1 auto;
       |  min-width: 0;
       |  max-width: 70ch;
       |}
       |.toc {
       |  flex: 0 0 13rem;
       |  position: sticky;
       |  top: 1.5rem;
       |  align-self: flex-start;
       |  max-height: calc(100vh - 3rem);
       |  overflow-y: auto;
       |  font-size: 0.82rem;
       |  line-height: 1.5;
       |  border-left: 1px solid var(--border);
       |  padding-left: 1rem;
       |}
       |.toc-title {
       |  font-weight: 700;
       |  text-transform: uppercase;
       |  letter-spacing: 0.05em;
       |  font-size: 0.7rem;
       |  color: var(--text-muted);
       |  margin-bottom: 0.5rem;
       |}
       |.toc nav ul { list-style: none; margin: 0; padding: 0; }
       |.toc nav li { margin: 0 0 0.25rem; }
       |.toc nav li.toc-sub { padding-left: 0.9rem; }
       |.toc a { color: var(--text-muted); text-decoration: none; }
       |.toc a:hover { color: var(--accent); text-decoration: underline; }
       |
       |@media (max-width: 55rem) {
       |  .layout { display: block; max-width: 70ch; }
       |  .prose { max-width: none; }
       |  .toc { display: none; }
       |}
       |
       |.to-top {
       |  position: fixed;
       |  right: 1.2rem;
       |  bottom: 1.2rem;
       |  width: 2.7rem;
       |  height: 2.7rem;
       |  display: flex;
       |  align-items: center;
       |  justify-content: center;
       |  border-radius: 50%;
       |  border: 1px solid var(--border);
       |  background: var(--bg-soft);
       |  color: var(--text);
       |  font-size: 1.25rem;
       |  line-height: 1;
       |  cursor: pointer;
       |  opacity: 0;
       |  pointer-events: none;
       |  transition: opacity 0.2s ease, color 0.2s ease, border-color 0.2s ease;
       |  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.18);
       |}
       |.to-top.show { opacity: 1; pointer-events: auto; }
       |.to-top:hover { color: var(--accent); border-color: var(--accent); }
       |
       |h1, h2, h3, h4 {
       |  line-height: 1.25;
       |  margin: 2em 0 0.6em;
       |  font-weight: 700;
       |}
       |h1 { font-size: 1.85em; margin-top: 0.4em; border-bottom: 4px solid var(--rule); padding-bottom: 0.2em; }
       |h2 { font-size: 1.4em; }
       |h3 { font-size: 1.15em; }
       |h4 { font-size: 1em; color: var(--text-muted); }
       |
       |p { margin: 0 0 1.1em; }
       |p, li { overflow-wrap: break-word; }
       |
       |strong { font-weight: 700; }
       |em { font-style: italic; }
       |
       |a {
       |  color: var(--accent);
       |  text-decoration: underline;
       |  text-decoration-thickness: 1px;
       |  text-underline-offset: 0.15em;
       |}
       |a:hover { color: var(--accent-hover); }
       |
       |ul, ol {
       |  margin: 0 0 1.1em;
       |  padding-left: 1.5em;
       |}
       |li { margin-bottom: 0.3em; }
       |li > ul, li > ol {
       |  margin-top: 0.3em;
       |  margin-bottom: 0.3em;
       |}
       |
       |blockquote {
       |  margin: 1.2em 0;
       |  padding: 0.2em 1.1em;
       |  border-left: 3px solid var(--quote-border);
       |  color: var(--text-muted);
       |}
       |blockquote p:last-child { margin-bottom: 0; }
       |
       |.post-byline {
       |  font-style: italic;
       |  font-size: 0.92em;
       |}
       |
       |hr {
       |  border: none;
       |  border-top: 1px solid var(--border);
       |  margin: 2.5em 0;
       |}
       |
       |img {
       |  max-width: 100%;
       |  height: auto;
       |}
       |
       |code, pre {
       |  font-family: var(--mono);
       |}
       |code {
       |  background: var(--code-bg);
       |  color: var(--code-text);
       |  border-radius: 4px;
       |  padding: 0.12em 0.35em;
       |  font-size: 0.88em;
       |  overflow-wrap: break-word;
       |}
       |pre {
       |  background: var(--code-bg);
       |  border: 1px solid var(--border);
       |  border-radius: 6px;
       |  padding: 0.9rem 1.1rem;
       |  margin: 1.2em 0;
       |  overflow-x: auto;
       |  line-height: 1.5;
       |}
       |pre > code {
       |  background: none;
       |  border-radius: 0;
       |  padding: 0;
       |  font-size: 0.85em;
       |  overflow-wrap: normal;
       |}
       |
       |.tok-kw { color: var(--tok-kw); font-weight: 700; }
       |.tok-soft { color: var(--tok-soft); }
       |.tok-str { color: var(--tok-str); }
       |.tok-num { color: var(--tok-num); }
       |.tok-comment { color: var(--tok-comment); font-style: italic; }
       |.tok-type { color: var(--tok-type); }
       |.tok-def { color: var(--tok-def); font-weight: 600; }
       |
       |table {
       |  display: block;
       |  width: max-content;
       |  max-width: 100%;
       |  overflow-x: auto;
       |  border-collapse: collapse;
       |  margin: 1.2em 0;
       |  font-size: 0.95em;
       |}
       |th, td {
       |  border: 1px solid var(--border);
       |  padding: 0.45em 0.8em;
       |  text-align: left;
       |  vertical-align: top;
       |}
       |thead th {
       |  background: var(--bg-soft);
       |  font-weight: 600;
       |}
       |
       |sup.fn-ref { font-size: 0.72em; line-height: 0; white-space: nowrap; }
       |sup.fn-ref a { text-decoration: none; padding: 0 0.1em; }
       |.footnotes { margin-top: 2.5em; font-size: 0.9em; color: var(--text-muted); }
       |.footnotes ol { padding-left: 1.3em; }
       |.footnotes li { margin-bottom: 0.5em; }
       |.footnotes .fn-back { text-decoration: none; margin-left: 0.3em; }
       |
       |.site-footer {
       |  border-top: 1px solid var(--border);
       |  color: var(--text-muted);
       |  font-size: 0.85rem;
       |}
       |.site-footer .wrap {
       |  padding-block: 1rem;
       |  display: flex;
       |  flex-wrap: wrap;
       |  gap: 0.5rem 1.5rem;
       |  justify-content: space-between;
       |}
       |.site-footer a { color: var(--text-muted); }
       |.site-footer a:hover { color: var(--accent); }
       |
       |@media (max-width: 26rem) {
       |  .site-nav { gap: 0.7rem; }
       |  .brand { font-size: 1rem; }
       |}
       |</style>
       |<script>
       |$themeScript
       |</script>
       |</head>
       |<body>
       |
       |<header class="site-header">
       |  <div class="wrap">
       |    <a class="brand" href="../">${wordmark()}</a>
       |    <nav class="site-nav" aria-label="Site">
       |      <a href="https://bjornregnell.se">BR</a>
       |      <a href="index.html">Blog</a>
       |      <select id="theme-select" class="theme-select" aria-label="Color theme"></select>
       |    </nav>
       |  </div>
       |</header>
       |
       |<main>
       |  <div class="layout">
       |    <article class="prose">
       |{{CONTENT}}
       |    </article>
       |{{TOC}}
       |  </div>
       |</main>
       |
       |<footer class="site-footer">
       |  <div class="wrap">
       |    <span>Björn Regnell</span>
       |    <a href="https://bjornregnell.se">bjornregnell.se</a>
       |  </div>
       |</footer>
       |
       |<button id="to-top" class="to-top" aria-label="Scroll to top" title="Scroll to top">↑</button>
       |<script>
       |(function () {
       |  var btn = document.getElementById("to-top");
       |  if (!btn) return;
       |  function onScroll() {
       |    if (window.scrollY > 400) btn.classList.add("show");
       |    else btn.classList.remove("show");
       |  }
       |  window.addEventListener("scroll", onScroll, { passive: true });
       |  btn.addEventListener("click", function () {
       |    window.scrollTo({ top: 0, behavior: "smooth" });
       |  });
       |  onScroll();
       |})();
       |</script>
       |
       |</body>
       |</html>
       |""".stripMargin

  // ---------- mascot-lab-GENERATED.html: Forgy & Smither, v1 geometric takes ----------
  // Forgy = the FEMALE twin (BR 2026-07-20), the hot impulsive one: hammer, HIO/VRO accents, Forgy dark.
  // Smither = the male twin, calm + methodical: TONGS (= human control) gripping a freshly-forged
  // GLOWING AXE HEAD (the axe = the palette's origin motif), TIP/temper-blue accents, Smither light.
  // Tableau: Forgy left, the anvil center, Smither right holding the hot axe head over the iron.
  // All fills interpolate the palette, so mascots re-skin when the palette moves. Charmingly primitive v1.

  def forgySvg: String =
    s"""<g>
       |  <ellipse cx="144" cy="66" rx="12" ry="26" transform="rotate(22 144 66)" fill="${vro.hex}"/>
       |  <circle cx="100" cy="80" r="34" fill="${ctip.hex}" stroke="${acg.hex}" stroke-width="3"/>
       |  <path d="M66 80 A34 34 0 0 1 134 80 L134 74 Q118 60 112 66 Q100 48 78 58 Q68 64 66 74 Z" fill="${vro.hex}"/>
       |  <circle cx="88" cy="90" r="4" fill="${tip.hex}"/>
       |  <circle cx="112" cy="90" r="4" fill="${tip.hex}"/>
       |  <path d="M88 102 Q100 112 112 102" stroke="${tip.hex}" stroke-width="3" fill="none" stroke-linecap="round"/>
       |  <path d="M70 114 L130 114 L146 210 L54 210 Z" fill="${hio.hex}"/>
       |  <path d="M84 130 L116 130 L124 200 L76 200 Z" fill="${ash.hex}"/>
       |  <line x1="70" y1="130" x2="36" y2="104" stroke="${hio.hex}" stroke-width="12" stroke-linecap="round"/>
       |  <line x1="36" y1="104" x2="22" y2="64" stroke="${acg.hex}" stroke-width="7" stroke-linecap="round"/>
       |  <rect x="4" y="50" width="38" height="17" rx="3" fill="${acg.hex}"/>
       |  <circle cx="52" cy="56" r="6" fill="${vro.hex}" opacity="0.25"/>
       |  <circle cx="52" cy="58" r="3" fill="${vro.hex}"/>
       |  <circle cx="60" cy="42" r="2.5" fill="${vro.hex}"/>
       |  <circle cx="44" cy="38" r="2" fill="${hio.hex}"/>
       |  <line x1="130" y1="130" x2="158" y2="168" stroke="${hio.hex}" stroke-width="12" stroke-linecap="round"/>
       |  <rect x="82" y="210" width="12" height="28" fill="${ash.hex}"/>
       |  <rect x="106" y="210" width="12" height="28" fill="${ash.hex}"/>
       |  <rect x="76" y="236" width="22" height="8" rx="3" fill="${acg.hex}"/>
       |  <rect x="102" y="236" width="22" height="8" rx="3" fill="${acg.hex}"/>
       |</g>""".stripMargin

  def smitherSvg: String =
    s"""<g>
       |  <circle cx="100" cy="80" r="34" fill="${ctip.hex}" stroke="${acg.hex}" stroke-width="3"/>
       |  <path d="M68 72 A32 32 0 0 1 132 72 Z" fill="${ash.hex}"/>
       |  <circle cx="88" cy="90" r="8" stroke="${tb.hex}" stroke-width="2.5" fill="none"/>
       |  <circle cx="112" cy="90" r="8" stroke="${tb.hex}" stroke-width="2.5" fill="none"/>
       |  <line x1="96" y1="90" x2="104" y2="90" stroke="${tb.hex}" stroke-width="2.5"/>
       |  <circle cx="88" cy="90" r="3" fill="${tip.hex}"/>
       |  <circle cx="112" cy="90" r="3" fill="${tip.hex}"/>
       |  <line x1="90" y1="106" x2="110" y2="106" stroke="${tip.hex}" stroke-width="3" stroke-linecap="round"/>
       |  <path d="M70 114 L130 114 L140 210 L60 210 Z" fill="${tb.hex}"/>
       |  <rect x="66" y="158" width="68" height="10" fill="${ash.hex}"/>
       |  <line x1="70" y1="132" x2="38" y2="158" stroke="${tb.hex}" stroke-width="12" stroke-linecap="round"/>
       |  <line x1="38" y1="158" x2="10" y2="148" stroke="${acg.hex}" stroke-width="5" stroke-linecap="round"/>
       |  <line x1="38" y1="158" x2="12" y2="170" stroke="${acg.hex}" stroke-width="5" stroke-linecap="round"/>
       |  <circle cx="38" cy="158" r="5" fill="${acg.hex}"/>
       |  <circle cx="-2" cy="157" r="18" fill="${hio.hex}" opacity="0.2"/>
       |  <path d="M-14 144 L10 149 L8 171 L-12 167 Q-23 156 -14 144 Z" fill="${hio.hex}"/>
       |  <path d="M-12 167 Q-23 156 -14 144" stroke="${vro.hex}" stroke-width="3" fill="none" stroke-linecap="round"/>
       |  <line x1="130" y1="132" x2="156" y2="172" stroke="${tb.hex}" stroke-width="12" stroke-linecap="round"/>
       |  <rect x="82" y="210" width="12" height="28" fill="${ash.hex}"/>
       |  <rect x="106" y="210" width="12" height="28" fill="${ash.hex}"/>
       |  <rect x="76" y="236" width="22" height="8" rx="3" fill="${acg.hex}"/>
       |  <rect x="102" y="236" width="22" height="8" rx="3" fill="${acg.hex}"/>
       |</g>""".stripMargin

  def anvilSvg: String =
    s"""<g>
       |  <rect x="20" y="44" width="120" height="18" rx="4" fill="${ash.hex}" stroke="${acg.hex}" stroke-width="3"/>
       |  <path d="M20 44 L20 62 L0 53 Z" fill="${ash.hex}" stroke="${acg.hex}" stroke-width="3"/>
       |  <rect x="62" y="62" width="36" height="16" fill="${ash.hex}" stroke="${acg.hex}" stroke-width="3"/>
       |  <rect x="48" y="78" width="64" height="14" rx="3" fill="${ash.hex}" stroke="${acg.hex}" stroke-width="3"/>
       |</g>""".stripMargin

  def mascotLab: String =
    def tableau =
      s"""<svg viewBox="0 0 640 300" width="640" role="img" aria-label="Forgy and Smither at the anvil">
         |  <line x1="10" y1="283" x2="630" y2="283" stroke="${cacg.hex}" stroke-width="2" opacity="0.5"/>
         |  <g transform="translate(286,39) scale(-1,1)">$forgySvg</g>
         |  <g transform="translate(240,191)">$anvilSvg</g>
         |  <g transform="translate(328,39)">$smitherSvg</g>
         |</svg>""".stripMargin
    def solo(svg: String, label: String) =
      s"""<figure><svg viewBox="-26 0 226 260" width="190" role="img" aria-label="$label">$svg</svg><figcaption>$label</figcaption></figure>"""
    s"""<!DOCTYPE html>
       |<html lang="en">
       |<head>
       |<meta charset="utf-8">
       |<meta name="viewport" content="width=device-width, initial-scale=1">
       |<title>genscalator mascot lab — Forgy &amp; Smither</title>
       |$generatedNote
       |<style>
       |  * { box-sizing: border-box; margin: 0; }
       |  body { font-family: "Fira Sans", system-ui, sans-serif; background: #888; padding: 1rem; }
       |  .lab { max-width: 1100px; margin: 0 auto; display: grid; gap: 1rem; }
       |  .panel { border-radius: 8px; padding: 1.5rem 2rem; }
       |  .tip { background: ${tip.hex}; } .light { background: ${ctip.hex}; }
       |  .label { font-size: .75rem; color: #ccc; font-family: "Fira Code", monospace; margin: 0 0 .6rem; }
       |  .light .label { color: #555; }
       |  .row { display: flex; gap: 2rem; align-items: flex-end; flex-wrap: wrap; }
       |  figure { text-align: center; }
       |  figcaption { font-family: "Fira Code", monospace; font-size: .8rem; color: #999; margin-top: .3rem; }
       |</style>
       |</head>
       |<body>
       |<div class="lab">
       |  <section class="panel tip">
       |    <div class="label">v1 geometric takes — Forgy (female, hammer, the hot one) · Smither (male, tongs = human control, holding a glowing ember) — iterate in DesignLang.scala</div>
       |    <div class="row">
       |      ${solo(forgySvg, "Forgy")}
       |      ${solo(smitherSvg, "Smither")}
       |    </div>
       |  </section>
       |  <section class="panel tip">
       |    <div class="label">the tableau: Forgy · the anvil · Smither, whose tongs hold a freshly-forged GLOWING AXE HEAD (VRO edge) over the iron</div>
       |    $tableau
       |  </section>
       |  <section class="panel light">
       |    <div class="label">same tableau on Smither light</div>
       |    $tableau
       |  </section>
       |</div>
       |</body>
       |</html>
       |""".stripMargin
}

@main def generateDesignLanguage(outDir: String*): Unit =
  import java.nio.file.{Files, Path}
  val dir = outDir.headOption.map(Path.of(_)).getOrElse {
    val next = Path.of("media", "design-language") // run from the repo root
    if Files.isDirectory(next) then next else Path.of(".") // or from this dir
  }
  val outputs = Vector(
    "README.md"                 -> DesignLang.readme,
    "index.html"                -> DesignLang.index,
    "design.css"                -> DesignLang.designCss,
    "design.js"                 -> DesignLang.designJs,
    "preview-GENERATED.html"    -> DesignLang.preview,
    "logo-lab-GENERATED.html"   -> DesignLang.logoLab,
    "mascot-lab-GENERATED.html" -> DesignLang.mascotLab,
    "../blog/_template.html" -> DesignLang.blogTemplate, // ssg's fixed template name (media/blog is our SIBLING since SM142); generated so the blog palette cannot drift
  )
  for (name, content) <- outputs do
    Files.writeString(dir.resolve(name), content)
    println(s"DesignLang: wrote $name (${content.linesIterator.size} lines)")
