/* GENERATED by DesignLang.scala - DO NOT EDIT. The four-theme dropdown: applies the saved
   theme before first paint, fills <select id="theme-select"> (styled by design.css),
   persists in localStorage; first visit follows the OS scheme (Smither/Forgy pair). */
(function () {
  var KEY = "gs-theme";
  var THEMES = [{v:"forgy-dark",l:"Forgy dark"},{v:"smither-light",l:"Smither light"},{v:"calm-dark",l:"Calm dark"},{v:"calm-light",l:"Calm light"}];
  var root = document.documentElement;
  function get() {
    try {
      var v = localStorage.getItem(KEY);
      if (!v) { /* migrate the two legacy two-state keys */
        var old = localStorage.getItem("br-theme") || localStorage.getItem("gs-design-theme");
        if (old === "dark") v = "forgy-dark";
        if (old === "light") v = "smither-light";
      }
      return THEMES.some(function (t) { return t.v === v; }) ? v : null;
    } catch (e) { return null; }
  }
  function apply(v) {
    if (v) root.setAttribute("data-theme", v);
    else root.removeAttribute("data-theme"); /* follow the OS pair */
  }
  apply(get()); /* before first paint */
  document.addEventListener("DOMContentLoaded", function () {
    var sel = document.getElementById("theme-select");
    if (!sel) return;
    THEMES.forEach(function (t) {
      var o = document.createElement("option");
      o.value = t.v;
      o.textContent = t.l;
      sel.appendChild(o);
    });
    var osDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
    sel.value = get() || (osDark ? "forgy-dark" : "smither-light");
    sel.addEventListener("change", function () {
      try { localStorage.setItem(KEY, sel.value); } catch (e) { /* still apply for this page */ }
      apply(sel.value);
    });
  });
})();
